package com.sbm.selfServices.model.views.ro;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 04 07:17:28 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CalcTotalMonthsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CalcTotalMonthsImpl() {
    }


    /**
     * Returns the bind variable value for PERSON_ID_BIND.
     * @return bind variable value for PERSON_ID_BIND
     */
    public String getPERSON_ID_BIND() {
        return (String)getNamedWhereClauseParam("PERSON_ID_BIND");
    }

    /**
     * Sets <code>value</code> for bind variable PERSON_ID_BIND.
     * @param value value to bind as PERSON_ID_BIND
     */
    public void setPERSON_ID_BIND(String value) {
        setNamedWhereClauseParam("PERSON_ID_BIND", value);
    }
}
