package com.sbm.selfServices.model.views.ro;

import java.sql.ResultSet;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 23 15:26:10 AST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookUpValuesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LookUpValuesViewImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * Returns the bind variable value for BV_LOOKUP_TYPE_ID.
     * @return bind variable value for BV_LOOKUP_TYPE_ID
     */
    public Number getBV_LOOKUP_TYPE_ID() {
        return (Number)getNamedWhereClauseParam("BV_LOOKUP_TYPE_ID");
    }

    /**
     * Sets <code>value</code> for bind variable BV_LOOKUP_TYPE_ID.
     * @param value value to bind as BV_LOOKUP_TYPE_ID
     */
    public void setBV_LOOKUP_TYPE_ID(Number value) {
        setNamedWhereClauseParam("BV_LOOKUP_TYPE_ID", value);
    }

    /**
     * Returns the bind variable value for BV_LOOKUP_VALUE_ID.
     * @return bind variable value for BV_LOOKUP_VALUE_ID
     */
    public Number getBV_LOOKUP_VALUE_ID() {
        return (Number)getNamedWhereClauseParam("BV_LOOKUP_VALUE_ID");
    }

    /**
     * Sets <code>value</code> for bind variable BV_LOOKUP_VALUE_ID.
     * @param value value to bind as BV_LOOKUP_VALUE_ID
     */
    public void setBV_LOOKUP_VALUE_ID(Number value) {
        setNamedWhereClauseParam("BV_LOOKUP_VALUE_ID", value);
    }
}
