package com.sbm.selfServices.model.views.ro;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 01 15:02:21 AST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OvertimeROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OvertimeROVOImpl() {
    }

    /**
     * Returns the bind variable value for BV_REQ_TYPE_ID.
     * @return bind variable value for BV_REQ_TYPE_ID
     */
    public String getBV_REQ_TYPE_ID() {
        return (String)getNamedWhereClauseParam("BV_REQ_TYPE_ID");
    }

    /**
     * Sets <code>value</code> for bind variable BV_REQ_TYPE_ID.
     * @param value value to bind as BV_REQ_TYPE_ID
     */
    public void setBV_REQ_TYPE_ID(String value) {
        setNamedWhereClauseParam("BV_REQ_TYPE_ID", value);
    }

    /**
     * Returns the bind variable value for BV_STEP_ID.
     * @return bind variable value for BV_STEP_ID
     */
    public String getBV_STEP_ID() {
        return (String)getNamedWhereClauseParam("BV_STEP_ID");
    }

    /**
     * Sets <code>value</code> for bind variable BV_STEP_ID.
     * @param value value to bind as BV_STEP_ID
     */
    public void setBV_STEP_ID(String value) {
        setNamedWhereClauseParam("BV_STEP_ID", value);
    }
}
