package com.sbm.selfServices.model.views.ro;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 01 15:02:19 AST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OvertimeROVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OvertimeROVORowImpl() {
    }
}
