package com.sbm.selfServices.model.views.ro;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 04 10:28:00 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestStepsCEOROViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RequestStepsCEOROViewImpl() {
    }

    /**
     * Returns the bind variable value for bv_stepId.
     * @return bind variable value for bv_stepId
     */
    public String getbv_stepId() {
        return (String) getNamedWhereClauseParam("bv_stepId");
    }

    /**
     * Sets <code>value</code> for bind variable bv_stepId.
     * @param value value to bind as bv_stepId
     */
    public void setbv_stepId(String value) {
        setNamedWhereClauseParam("bv_stepId", value);
    }

    /**
     * Returns the bind variable value for bv_requestName.
     * @return bind variable value for bv_requestName
     */
    public String getbv_requestName() {
        return (String) getNamedWhereClauseParam("bv_requestName");
    }

    /**
     * Sets <code>value</code> for bind variable bv_requestName.
     * @param value value to bind as bv_requestName
     */
    public void setbv_requestName(String value) {
        setNamedWhereClauseParam("bv_requestName", value);
    }
}

