package com.sbm.selfServices.model.entities;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 20 19:09:51 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestSteps_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        StepId {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getStepId();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setStepId((Number)value);
            }
        }
        ,
        StepName {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getStepName();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setStepName((String)value);
            }
        }
        ,
        NextStepId {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getNextStepId();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setNextStepId((Number)value);
            }
        }
        ,
        RequestTypeId {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getRequestTypeId();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setRequestTypeId((Number)value);
            }
        }
        ,
        BudgetValidation {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getBudgetValidation();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setBudgetValidation((String)value);
            }
        }
        ,
        StepType {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getStepType();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setStepType((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedOn {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getLastUpdatedOn();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setLastUpdatedOn((Timestamp)value);
            }
        }
        ,
        CreatedBy {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedOn {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getCreatedOn();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setCreatedOn((Timestamp)value);
            }
        }
        ,
        RowID {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getRowID();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SpecialEdit {
            public Object get(RequestSteps_EOImpl obj) {
                return obj.getSpecialEdit();
            }

            public void put(RequestSteps_EOImpl obj, Object value) {
                obj.setSpecialEdit((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(RequestSteps_EOImpl object);

        public abstract void put(RequestSteps_EOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int STEPNAME = AttributesEnum.StepName.index();
    public static final int NEXTSTEPID = AttributesEnum.NextStepId.index();
    public static final int REQUESTTYPEID = AttributesEnum.RequestTypeId.index();
    public static final int BUDGETVALIDATION = AttributesEnum.BudgetValidation.index();
    public static final int STEPTYPE = AttributesEnum.StepType.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDON = AttributesEnum.LastUpdatedOn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SPECIALEDIT = AttributesEnum.SpecialEdit.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestSteps_EOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sbm.selfServices.model.entities.RequestSteps_EO");
    }

    /**
     * Gets the attribute value for StepId, using the alias name StepId.
     * @return the StepId
     */
    public Number getStepId() {
        return (Number)getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepId.
     * @param value value to set the StepId
     */
    public void setStepId(Number value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for StepName, using the alias name StepName.
     * @return the StepName
     */
    public String getStepName() {
        return (String)getAttributeInternal(STEPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepName.
     * @param value value to set the StepName
     */
    public void setStepName(String value) {
        setAttributeInternal(STEPNAME, value);
    }

    /**
     * Gets the attribute value for NextStepId, using the alias name NextStepId.
     * @return the NextStepId
     */
    public Number getNextStepId() {
        return (Number)getAttributeInternal(NEXTSTEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextStepId.
     * @param value value to set the NextStepId
     */
    public void setNextStepId(Number value) {
        setAttributeInternal(NEXTSTEPID, value);
    }

    /**
     * Gets the attribute value for RequestTypeId, using the alias name RequestTypeId.
     * @return the RequestTypeId
     */
    public Number getRequestTypeId() {
        return (Number)getAttributeInternal(REQUESTTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestTypeId.
     * @param value value to set the RequestTypeId
     */
    public void setRequestTypeId(Number value) {
        setAttributeInternal(REQUESTTYPEID, value);
    }

    /**
     * Gets the attribute value for BudgetValidation, using the alias name BudgetValidation.
     * @return the BudgetValidation
     */
    public String getBudgetValidation() {
        return (String)getAttributeInternal(BUDGETVALIDATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetValidation.
     * @param value value to set the BudgetValidation
     */
    public void setBudgetValidation(String value) {
        setAttributeInternal(BUDGETVALIDATION, value);
    }

    /**
     * Gets the attribute value for StepType, using the alias name StepType.
     * @return the StepType
     */
    public String getStepType() {
        return (String)getAttributeInternal(STEPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepType.
     * @param value value to set the StepType
     */
    public void setStepType(String value) {
        setAttributeInternal(STEPTYPE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedOn, using the alias name LastUpdatedOn.
     * @return the LastUpdatedOn
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedOn.
     * @param value value to set the LastUpdatedOn
     */
    public void setLastUpdatedOn(Timestamp value) {
        setAttributeInternal(LASTUPDATEDON, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp)getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedOn.
     * @param value value to set the CreatedOn
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for RowID, using the alias name RowID.
     * @return the RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for SpecialEdit, using the alias name SpecialEdit.
     * @return the SpecialEdit
     */
    public String getSpecialEdit() {
        return (String)getAttributeInternal(SPECIALEDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecialEdit.
     * @param value value to set the SpecialEdit
     */
    public void setSpecialEdit(String value) {
        setAttributeInternal(SPECIALEDIT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        this.setCreatedOn(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        this.setLastUpdatedOn(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        this.setCreatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
        this.setLastUpdatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == EntityImpl.DML_UPDATE) {
            System.err.println("In DML UPDATE");
            this.setLastUpdatedBy(ADFContext.getCurrent().getSessionScope().get("userName").toString());
            this.setLastUpdatedOn(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        } 
        super.doDML(operation, e);
    }
}
