package com.sbm.selfServices.model.entities;

import oracle.jbo.Key;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.Char;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 04 07:44:20 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestStepsCEO_EOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        StepId {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getStepId();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setStepId((Number) value);
            }
        }
        ,
        StepName {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getStepName();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setStepName((String) value);
            }
        }
        ,
        NextStepId {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getNextStepId();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setNextStepId((Number) value);
            }
        }
        ,
        RequestTypeId {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getRequestTypeId();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setRequestTypeId((Number) value);
            }
        }
        ,
        BudgetValidation {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getBudgetValidation();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setBudgetValidation((String) value);
            }
        }
        ,
        StepType {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getStepType();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setStepType((String) value);
            }
        }
        ,
        LastUpdatedBy {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setLastUpdatedBy((String) value);
            }
        }
        ,
        LastUpdatedOn {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getLastUpdatedOn();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setLastUpdatedOn((Timestamp) value);
            }
        }
        ,
        CreatedBy {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getCreatedBy();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setCreatedBy((String) value);
            }
        }
        ,
        CreatedOn {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getCreatedOn();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setCreatedOn((Timestamp) value);
            }
        }
        ,
        RowID {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getRowID();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SpecialEdit {
            protected Object get(RequestStepsCEO_EOImpl obj) {
                return obj.getSpecialEdit();
            }

            protected void put(RequestStepsCEO_EOImpl obj, Object value) {
                obj.setSpecialEdit((String) value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }


        protected abstract Object get(RequestStepsCEO_EOImpl object);

        protected abstract void put(RequestStepsCEO_EOImpl object, Object value);
    }


    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int STEPNAME = AttributesEnum.StepName.index();
    public static final int NEXTSTEPID = AttributesEnum.NextStepId.index();
    public static final int REQUESTTYPEID = AttributesEnum.RequestTypeId.index();
    public static final int BUDGETVALIDATION = AttributesEnum.BudgetValidation.index();
    public static final int STEPTYPE = AttributesEnum.StepType.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDON = AttributesEnum.LastUpdatedOn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SPECIALEDIT = AttributesEnum.SpecialEdit.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestStepsCEO_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.sbm.selfServices.model.entities.RequestStepsCEO_EO");
    }


    /**
     * Gets the attribute value for StepId, using the alias name StepId.
     * @return the value of StepId
     */
    public Number getStepId() {
        return (Number) getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepId.
     * @param value value to set the StepId
     */
    public void setStepId(Number value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for StepName, using the alias name StepName.
     * @return the value of StepName
     */
    public String getStepName() {
        return (String) getAttributeInternal(STEPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepName.
     * @param value value to set the StepName
     */
    public void setStepName(String value) {
        setAttributeInternal(STEPNAME, value);
    }

    /**
     * Gets the attribute value for NextStepId, using the alias name NextStepId.
     * @return the value of NextStepId
     */
    public Number getNextStepId() {
        return (Number) getAttributeInternal(NEXTSTEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextStepId.
     * @param value value to set the NextStepId
     */
    public void setNextStepId(Number value) {
        setAttributeInternal(NEXTSTEPID, value);
    }

    /**
     * Gets the attribute value for RequestTypeId, using the alias name RequestTypeId.
     * @return the value of RequestTypeId
     */
    public Number getRequestTypeId() {
        return (Number) getAttributeInternal(REQUESTTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestTypeId.
     * @param value value to set the RequestTypeId
     */
    public void setRequestTypeId(Number value) {
        setAttributeInternal(REQUESTTYPEID, value);
    }

    /**
     * Gets the attribute value for BudgetValidation, using the alias name BudgetValidation.
     * @return the value of BudgetValidation
     */
    public String getBudgetValidation() {
        return (String) getAttributeInternal(BUDGETVALIDATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetValidation.
     * @param value value to set the BudgetValidation
     */
    public void setBudgetValidation(String value) {
        setAttributeInternal(BUDGETVALIDATION, value);
    }

    /**
     * Gets the attribute value for StepType, using the alias name StepType.
     * @return the value of StepType
     */
    public String getStepType() {
        return (String) getAttributeInternal(STEPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepType.
     * @param value value to set the StepType
     */
    public void setStepType(String value) {
        setAttributeInternal(STEPTYPE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedOn, using the alias name LastUpdatedOn.
     * @return the value of LastUpdatedOn
     */
    public Timestamp getLastUpdatedOn() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedOn.
     * @param value value to set the LastUpdatedOn
     */
    public void setLastUpdatedOn(Timestamp value) {
        setAttributeInternal(LASTUPDATEDON, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedOn.
     * @param value value to set the CreatedOn
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for RowID, using the alias name RowID.
     * @return the value of RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for SpecialEdit, using the alias name SpecialEdit.
     * @return the value of SpecialEdit
     */
    public String getSpecialEdit() {
        return (String) getAttributeInternal(SPECIALEDIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecialEdit.
     * @param value value to set the SpecialEdit
     */
    public void setSpecialEdit(String value) {
        setAttributeInternal(SPECIALEDIT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param specialEdit key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String specialEdit) {
        return new Key(new Object[] { specialEdit });
    }


}

