package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 14 09:44:41 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprovalHistoryCeoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprovalHistoryCeoVOImpl() {
    }

    /**
     * Returns the bind variable value for req_name.
     * @return bind variable value for req_name
     */
    public String getreq_name() {
        return (String)getNamedWhereClauseParam("req_name");
    }

    /**
     * Sets <code>value</code> for bind variable req_name.
     * @param value value to bind as req_name
     */
    public void setreq_name(String value) {
        setNamedWhereClauseParam("req_name", value);
    }
}
