package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 06 05:18:45 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BusinessTripRequestViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BusinessTripRequestViewImpl() {
    }

    /**
     * Returns the variable value for bind_assignee.
     * @return variable value for bind_assignee
     */
    public String getbind_assignee() {
        return (String)ensureVariableManager().getVariableValue("bind_assignee");
    }

    /**
     * Sets <code>value</code> for variable bind_assignee.
     * @param value value to bind as bind_assignee
     */
    public void setbind_assignee(String value) {
        ensureVariableManager().setVariableValue("bind_assignee", value);
    }

    /**
     * Returns the variable value for bind_PersonNumber.
     * @return variable value for bind_PersonNumber
     */
    public String getbind_PersonNumber() {
        return (String)ensureVariableManager().getVariableValue("bind_PersonNumber");
    }

    /**
     * Sets <code>value</code> for variable bind_PersonNumber.
     * @param value value to bind as bind_PersonNumber
     */
    public void setbind_PersonNumber(String value) {
        ensureVariableManager().setVariableValue("bind_PersonNumber", value);
    }

    /**
     * Returns the variable value for bind_assignee2.
     * @return variable value for bind_assignee2
     */
    public String getbind_assignee2() {
        return (String)ensureVariableManager().getVariableValue("bind_assignee2");
    }

    /**
     * Sets <code>value</code> for variable bind_assignee2.
     * @param value value to bind as bind_assignee2
     */
    public void setbind_assignee2(String value) {
        ensureVariableManager().setVariableValue("bind_assignee2", value);
    }
	
	

    /**
     * Returns the variable value for bind_tripType.
     * @return variable value for bind_tripType
     */
    public String getbind_tripType() {
        return (String)ensureVariableManager().getVariableValue("bind_tripType");
    }

    /**
     * Sets <code>value</code> for variable bind_tripType.
     * @param value value to bind as bind_tripType
     */
    public void setbind_tripType(String value) {
        ensureVariableManager().setVariableValue("bind_tripType", value);
    }
}
