package com.sbm.selfServices.model.views.up;

import com.sbm.selfServices.model.entities.BusinessTripRequestImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 06 05:18:45 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BusinessTripRequestViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LocalBusinessTripId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getLocalBusinessTripId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setLocalBusinessTripId((DBSequence)value);
            }
        }
        ,
        PersoneId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersoneId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersoneId((String)value);
            }
        }
        ,
        StepId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getStepId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setStepId((Long)value);
            }
        }
        ,
        StartDate {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        Days {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDays();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setDays((Number)value);
            }
        }
        ,
        CountryId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCountryId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCountryId((Number)value);
            }
        }
        ,
        CityId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCityId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCityId((Number)value);
            }
        }
        ,
        DestinationId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDestinationId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setDestinationId((String)value);
            }
        }
        ,
        LaundryAllowanceAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getLaundryAllowanceAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setLaundryAllowanceAmount((Number)value);
            }
        }
        ,
        TransportationAllowanceType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTransportationAllowanceType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTransportationAllowanceType((String)value);
            }
        }
        ,
        TransAllowanceAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTransAllowanceAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTransAllowanceAmount((Number)value);
            }
        }
        ,
        HousingAllowanceType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getHousingAllowanceType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setHousingAllowanceType((String)value);
            }
        }
        ,
        HousingAllowanceAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getHousingAllowanceAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setHousingAllowanceAmount((Number)value);
            }
        }
        ,
        FoodAllowanceType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getFoodAllowanceType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setFoodAllowanceType((String)value);
            }
        }
        ,
        FoodAllowanceAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getFoodAllowanceAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setFoodAllowanceAmount((Number)value);
            }
        }
        ,
        MeansTravel {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getMeansTravel();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setMeansTravel((String)value);
            }
        }
        ,
        VisaCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getVisaCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setVisaCost((Number)value);
            }
        }
        ,
        OtherCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherCost((Number)value);
            }
        }
        ,
        BudgetFlag {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getBudgetFlag();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setBudgetFlag((String)value);
            }
        }
        ,
        TripType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTripType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTripType((String)value);
            }
        }
        ,
        PersoneName {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersoneName();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersoneName((String)value);
            }
        }
        ,
        RequestStatus {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        RejectComments {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getRejectComments();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setRejectComments((String)value);
            }
        }
        ,
        Assignee {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getAssignee();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAssignee((String)value);
            }
        }
        ,
        TripReason {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTripReason();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTripReason((String)value);
            }
        }
        ,
        EventSubject {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEventSubject();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setEventSubject((String)value);
            }
        }
        ,
        EventType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEventType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setEventType((String)value);
            }
        }
        ,
        RequiredVisa {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getRequiredVisa();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setRequiredVisa((String)value);
            }
        }
        ,
        TargetedCompetencies {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTargetedCompetencies();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTargetedCompetencies((String)value);
            }
        }
        ,
        CourseName {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCourseName();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCourseName((String)value);
            }
        }
        ,
        ExpenseBusinessTripId {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getExpenseBusinessTripId();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setExpenseBusinessTripId((Number)value);
            }
        }
        ,
        ExpenseFlag {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getExpenseFlag();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setExpenseFlag((String)value);
            }
        }
        ,
        ExpenseType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getExpenseType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setExpenseType((String)value);
            }
        }
        ,
        CancelReason {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCancelReason();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCancelReason((String)value);
            }
        }
        ,
        SubType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getSubType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setSubType((String)value);
            }
        }
        ,
        NewCity {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getNewCity();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setNewCity((String)value);
            }
        }
        ,
        DestinationType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDestinationType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setDestinationType((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CostCenter {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCostCenter();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCostCenter((String)value);
            }
        }
        ,
        CostCenterNumber {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCostCenterNumber();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setCostCenterNumber((String)value);
            }
        }
        ,
        TrainingCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTrainingCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTrainingCost((Number)value);
            }
        }
        ,
        OtherMeansTravel {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherMeansTravel();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherMeansTravel((String)value);
            }
        }
        ,
        TravelCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTravelCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTravelCost((Number)value);
            }
        }
        ,
        EventCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEventCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setEventCost((Number)value);
            }
        }
        ,
        TripComment {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTripComment();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTripComment((String)value);
            }
        }
        ,
        PersonPosition {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersonPosition();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersonPosition((String)value);
            }
        }
        ,
        PersonJob {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersonJob();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersonJob((String)value);
            }
        }
        ,
        PersonDepartment {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersonDepartment();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersonDepartment((String)value);
            }
        }
        ,
        PersonLocation {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPersonLocation();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPersonLocation((String)value);
            }
        }
        ,
        OtherCities {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherCities();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherCities((String)value);
            }
        }
        ,
        ToCity {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getToCity();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setToCity((String)value);
            }
        }
        ,
        ActionTaken {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getActionTaken();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setActionTaken((String)value);
            }
        }
        ,
        TotalForInvoice {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTotalForInvoice();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTotalForInvoice((Number)value);
            }
        }
        ,
        AssigneeName {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getAssigneeName();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAssigneeName((String)value);
            }
        }
        ,
        PerDiemAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPerDiemAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPerDiemAmount((Number)value);
            }
        }
        ,
        BenefitType {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getBenefitType();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setBenefitType((String)value);
            }
        }
        ,
        Lob {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getLob();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setLob((String)value);
            }
        }
        ,
        Division {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDivision();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        ActualStartDate {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getActualStartDate();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setActualStartDate((Date)value);
            }
        }
        ,
        ActualEndDate {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getActualEndDate();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setActualEndDate((Date)value);
            }
        }
        ,
        OneWayTrip {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOneWayTrip();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOneWayTrip((String)value);
            }
        }
        ,
        MoreCitiesCheck {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getMoreCitiesCheck();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setMoreCitiesCheck((String)value);
            }
        }
        ,
        InvoiceNumber {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getInvoiceNumber();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setInvoiceNumber((String)value);
            }
        }
        ,
        TotalBtCost {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTotalBtCost();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTotalBtCost((Number)value);
            }
        }
        ,
        PaymentStatus {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPaymentStatus();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPaymentStatus((String)value);
            }
        }
        ,
        PreferredDepartureTime {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPreferredDepartureTime();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPreferredDepartureTime((Timestamp)value);
            }
        }
        ,
        PreferredArrivalTime {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getPreferredArrivalTime();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setPreferredArrivalTime((Timestamp)value);
            }
        }
        ,
        TotalAmount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTotalAmount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTotalAmount((Number)value);
            }
        }
        ,
        StepComment {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getStepComment();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setStepComment((String)value);
            }
        }
        ,
        attachmentRowCount {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getattachmentRowCount();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setattachmentRowCount((String)value);
            }
        }
        ,
        destinationTypeTrans {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getdestinationTypeTrans();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setdestinationTypeTrans((String)value);
            }
        }
        ,
        MoreCities {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getMoreCities();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setMoreCities((Boolean)value);
            }
        }
        ,
        OneWay_TRANS {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOneWay_TRANS();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOneWay_TRANS((Boolean)value);
            }
        }
        ,
        More_Cities_Check_Trans {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getMore_Cities_Check_Trans();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setMore_Cities_Check_Trans((Boolean)value);
            }
        }
        ,
        OtherCitiesTrans {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherCitiesTrans();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherCitiesTrans((String)value);
            }
        }
        ,
        EditRequest {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEditRequest();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setEditRequest((String)value);
            }
        }
        ,
        OtherByEmployee {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherByEmployee();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherByEmployee((Number)value);
            }
        }
        ,
        OtherByTatweer {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getOtherByTatweer();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setOtherByTatweer((Number)value);
            }
        }
        ,
        TrainingByEmployee {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTrainingByEmployee();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTrainingByEmployee((Number)value);
            }
        }
        ,
        TravelCostByEmployee {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTravelCostByEmployee();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setTravelCostByEmployee((Number)value);
            }
        }
        ,
        Declaration {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDeclaration();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setDeclaration((String)value);
            }
        }
        ,
        RequestAttachmentsView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getRequestAttachmentsView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ApprovalHistoryVO {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getApprovalHistoryVO();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TripTypeStaticView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getTripTypeStaticView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountriesLOV {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCountriesLOV();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CitiesLOV {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getCitiesLOV();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AllowanceTypeStaticView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getAllowanceTypeStaticView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RequestStepsROView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getRequestStepsROView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BusinessTripExpenseROView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getBusinessTripExpenseROView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EventTypeStaticView {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getEventTypeStaticView();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BusinessTripSubTypeStaticView1 {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getBusinessTripSubTypeStaticView1();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DestinationStaticView1 {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDestinationStaticView1();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DepartmentsLOV1 {
            public Object get(BusinessTripRequestViewRowImpl obj) {
                return obj.getDepartmentsLOV1();
            }

            public void put(BusinessTripRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;

        private static final int firstIndex = 0;

        public abstract Object get(BusinessTripRequestViewRowImpl object);

        public abstract void put(BusinessTripRequestViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LOCALBUSINESSTRIPID = AttributesEnum.LocalBusinessTripId.index();
    public static final int PERSONEID = AttributesEnum.PersoneId.index();
    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int DAYS = AttributesEnum.Days.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int CITYID = AttributesEnum.CityId.index();
    public static final int DESTINATIONID = AttributesEnum.DestinationId.index();
    public static final int LAUNDRYALLOWANCEAMOUNT = AttributesEnum.LaundryAllowanceAmount.index();
    public static final int TRANSPORTATIONALLOWANCETYPE = AttributesEnum.TransportationAllowanceType.index();
    public static final int TRANSALLOWANCEAMOUNT = AttributesEnum.TransAllowanceAmount.index();
    public static final int HOUSINGALLOWANCETYPE = AttributesEnum.HousingAllowanceType.index();
    public static final int HOUSINGALLOWANCEAMOUNT = AttributesEnum.HousingAllowanceAmount.index();
    public static final int FOODALLOWANCETYPE = AttributesEnum.FoodAllowanceType.index();
    public static final int FOODALLOWANCEAMOUNT = AttributesEnum.FoodAllowanceAmount.index();
    public static final int MEANSTRAVEL = AttributesEnum.MeansTravel.index();
    public static final int VISACOST = AttributesEnum.VisaCost.index();
    public static final int OTHERCOST = AttributesEnum.OtherCost.index();
    public static final int BUDGETFLAG = AttributesEnum.BudgetFlag.index();
    public static final int TRIPTYPE = AttributesEnum.TripType.index();
    public static final int PERSONENAME = AttributesEnum.PersoneName.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int REJECTCOMMENTS = AttributesEnum.RejectComments.index();
    public static final int ASSIGNEE = AttributesEnum.Assignee.index();
    public static final int TRIPREASON = AttributesEnum.TripReason.index();
    public static final int EVENTSUBJECT = AttributesEnum.EventSubject.index();
    public static final int EVENTTYPE = AttributesEnum.EventType.index();
    public static final int REQUIREDVISA = AttributesEnum.RequiredVisa.index();
    public static final int TARGETEDCOMPETENCIES = AttributesEnum.TargetedCompetencies.index();
    public static final int COURSENAME = AttributesEnum.CourseName.index();
    public static final int EXPENSEBUSINESSTRIPID = AttributesEnum.ExpenseBusinessTripId.index();
    public static final int EXPENSEFLAG = AttributesEnum.ExpenseFlag.index();
    public static final int EXPENSETYPE = AttributesEnum.ExpenseType.index();
    public static final int CANCELREASON = AttributesEnum.CancelReason.index();
    public static final int SUBTYPE = AttributesEnum.SubType.index();
    public static final int NEWCITY = AttributesEnum.NewCity.index();
    public static final int DESTINATIONTYPE = AttributesEnum.DestinationType.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int COSTCENTER = AttributesEnum.CostCenter.index();
    public static final int COSTCENTERNUMBER = AttributesEnum.CostCenterNumber.index();
    public static final int TRAININGCOST = AttributesEnum.TrainingCost.index();
    public static final int OTHERMEANSTRAVEL = AttributesEnum.OtherMeansTravel.index();
    public static final int TRAVELCOST = AttributesEnum.TravelCost.index();
    public static final int EVENTCOST = AttributesEnum.EventCost.index();
    public static final int TRIPCOMMENT = AttributesEnum.TripComment.index();
    public static final int PERSONPOSITION = AttributesEnum.PersonPosition.index();
    public static final int PERSONJOB = AttributesEnum.PersonJob.index();
    public static final int PERSONDEPARTMENT = AttributesEnum.PersonDepartment.index();
    public static final int PERSONLOCATION = AttributesEnum.PersonLocation.index();
    public static final int OTHERCITIES = AttributesEnum.OtherCities.index();
    public static final int TOCITY = AttributesEnum.ToCity.index();
    public static final int ACTIONTAKEN = AttributesEnum.ActionTaken.index();
    public static final int TOTALFORINVOICE = AttributesEnum.TotalForInvoice.index();
    public static final int ASSIGNEENAME = AttributesEnum.AssigneeName.index();
    public static final int PERDIEMAMOUNT = AttributesEnum.PerDiemAmount.index();
    public static final int BENEFITTYPE = AttributesEnum.BenefitType.index();
    public static final int LOB = AttributesEnum.Lob.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int ACTUALSTARTDATE = AttributesEnum.ActualStartDate.index();
    public static final int ACTUALENDDATE = AttributesEnum.ActualEndDate.index();
    public static final int ONEWAYTRIP = AttributesEnum.OneWayTrip.index();
    public static final int MORECITIESCHECK = AttributesEnum.MoreCitiesCheck.index();
    public static final int INVOICENUMBER = AttributesEnum.InvoiceNumber.index();
    public static final int TOTALBTCOST = AttributesEnum.TotalBtCost.index();
    public static final int PAYMENTSTATUS = AttributesEnum.PaymentStatus.index();
    public static final int PREFERREDDEPARTURETIME = AttributesEnum.PreferredDepartureTime.index();
    public static final int PREFERREDARRIVALTIME = AttributesEnum.PreferredArrivalTime.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int STEPCOMMENT = AttributesEnum.StepComment.index();
    public static final int ATTACHMENTROWCOUNT = AttributesEnum.attachmentRowCount.index();
    public static final int DESTINATIONTYPETRANS = AttributesEnum.destinationTypeTrans.index();
    public static final int MORECITIES = AttributesEnum.MoreCities.index();
    public static final int ONEWAY_TRANS = AttributesEnum.OneWay_TRANS.index();
    public static final int MORE_CITIES_CHECK_TRANS = AttributesEnum.More_Cities_Check_Trans.index();
    public static final int OTHERCITIESTRANS = AttributesEnum.OtherCitiesTrans.index();
    public static final int EDITREQUEST = AttributesEnum.EditRequest.index();
    public static final int OTHERBYEMPLOYEE = AttributesEnum.OtherByEmployee.index();
    public static final int OTHERBYTATWEER = AttributesEnum.OtherByTatweer.index();
    public static final int TRAININGBYEMPLOYEE = AttributesEnum.TrainingByEmployee.index();
    public static final int TRAVELCOSTBYEMPLOYEE = AttributesEnum.TravelCostByEmployee.index();
    public static final int DECLARATION = AttributesEnum.Declaration.index();
    public static final int REQUESTATTACHMENTSVIEW = AttributesEnum.RequestAttachmentsView.index();
    public static final int APPROVALHISTORYVO = AttributesEnum.ApprovalHistoryVO.index();
    public static final int TRIPTYPESTATICVIEW = AttributesEnum.TripTypeStaticView.index();
    public static final int COUNTRIESLOV = AttributesEnum.CountriesLOV.index();
    public static final int CITIESLOV = AttributesEnum.CitiesLOV.index();
    public static final int ALLOWANCETYPESTATICVIEW = AttributesEnum.AllowanceTypeStaticView.index();
    public static final int REQUESTSTEPSROVIEW = AttributesEnum.RequestStepsROView.index();
    public static final int BUSINESSTRIPEXPENSEROVIEW = AttributesEnum.BusinessTripExpenseROView.index();
    public static final int EVENTTYPESTATICVIEW = AttributesEnum.EventTypeStaticView.index();
    public static final int BUSINESSTRIPSUBTYPESTATICVIEW1 = AttributesEnum.BusinessTripSubTypeStaticView1.index();
    public static final int DESTINATIONSTATICVIEW1 = AttributesEnum.DestinationStaticView1.index();
    public static final int DEPARTMENTSLOV1 = AttributesEnum.DepartmentsLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BusinessTripRequestViewRowImpl() {
    }

    /**
     * Gets BusinessTripRequest entity object.
     * @return the BusinessTripRequest
     */
    public BusinessTripRequestImpl getBusinessTripRequest() {
        return (BusinessTripRequestImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LOCAL_BUSINESS_TRIP_ID using the alias name LocalBusinessTripId.
     * @return the LOCAL_BUSINESS_TRIP_ID
     */
    public DBSequence getLocalBusinessTripId() {
        return (DBSequence)getAttributeInternal(LOCALBUSINESSTRIPID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCAL_BUSINESS_TRIP_ID using the alias name LocalBusinessTripId.
     * @param value value to set the LOCAL_BUSINESS_TRIP_ID
     */
    public void setLocalBusinessTripId(DBSequence value) {
        setAttributeInternal(LOCALBUSINESSTRIPID, value);
    }

    /**
     * Gets the attribute value for PERSONE_ID using the alias name PersoneId.
     * @return the PERSONE_ID
     */
    public String getPersoneId() {
        return (String) getAttributeInternal(PERSONEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSONE_ID using the alias name PersoneId.
     * @param value value to set the PERSONE_ID
     */
    public void setPersoneId(String value) {
        setAttributeInternal(PERSONEID, value);
    }

    /**
     * Gets the attribute value for STEP_ID using the alias name StepId.
     * @return the STEP_ID
     */
    public Long getStepId() {
        return (Long) getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as attribute value for STEP_ID using the alias name StepId.
     * @param value value to set the STEP_ID
     */
    public void setStepId(Long value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for DAYS using the alias name Days.
     * @return the DAYS
     */
    public Number getDays() {
        return (Number) getAttributeInternal(DAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for DAYS using the alias name Days.
     * @param value value to set the DAYS
     */
    public void setDays(Number value) {
        setAttributeInternal(DAYS, value);
    }

    /**
     * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
     * @return the COUNTRY_ID
     */
    public Number getCountryId() {
        return (Number) getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
     * @param value value to set the COUNTRY_ID
     */
    public void setCountryId(Number value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for CITY_ID using the alias name CityId.
     * @return the CITY_ID
     */
    public Number getCityId() {
        return (Number) getAttributeInternal(CITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_ID using the alias name CityId.
     * @param value value to set the CITY_ID
     */
    public void setCityId(Number value) {
        setAttributeInternal(CITYID, value);
    }

    /**
     * Gets the attribute value for DESTINATION_ID using the alias name DestinationId.
     * @return the DESTINATION_ID
     */
    public String getDestinationId() {
        return (String) getAttributeInternal(DESTINATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_ID using the alias name DestinationId.
     * @param value value to set the DESTINATION_ID
     */
    public void setDestinationId(String value) {
        setAttributeInternal(DESTINATIONID, value);
    }

    /**
     * Gets the attribute value for LAUNDRY_ALLOWANCE_AMOUNT using the alias name LaundryAllowanceAmount.
     * @return the LAUNDRY_ALLOWANCE_AMOUNT
     */
    public Number getLaundryAllowanceAmount() {
        return (Number) getAttributeInternal(LAUNDRYALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LAUNDRY_ALLOWANCE_AMOUNT using the alias name LaundryAllowanceAmount.
     * @param value value to set the LAUNDRY_ALLOWANCE_AMOUNT
     */
    public void setLaundryAllowanceAmount(Number value) {
        setAttributeInternal(LAUNDRYALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for TRANSPORTATION_ALLOWANCE_TYPE using the alias name TransportationAllowanceType.
     * @return the TRANSPORTATION_ALLOWANCE_TYPE
     */
    public String getTransportationAllowanceType() {
        return (String) getAttributeInternal(TRANSPORTATIONALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORTATION_ALLOWANCE_TYPE using the alias name TransportationAllowanceType.
     * @param value value to set the TRANSPORTATION_ALLOWANCE_TYPE
     */
    public void setTransportationAllowanceType(String value) {
        setAttributeInternal(TRANSPORTATIONALLOWANCETYPE, value);
    }

    /**
     * Gets the attribute value for TRANS_ALLOWANCE_AMOUNT using the alias name TransAllowanceAmount.
     * @return the TRANS_ALLOWANCE_AMOUNT
     */
    public Number getTransAllowanceAmount() {
        return (Number) getAttributeInternal(TRANSALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANS_ALLOWANCE_AMOUNT using the alias name TransAllowanceAmount.
     * @param value value to set the TRANS_ALLOWANCE_AMOUNT
     */
    public void setTransAllowanceAmount(Number value) {
        setAttributeInternal(TRANSALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for HOUSING_ALLOWANCE_TYPE using the alias name HousingAllowanceType.
     * @return the HOUSING_ALLOWANCE_TYPE
     */
    public String getHousingAllowanceType() {
        return (String) getAttributeInternal(HOUSINGALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOUSING_ALLOWANCE_TYPE using the alias name HousingAllowanceType.
     * @param value value to set the HOUSING_ALLOWANCE_TYPE
     */
    public void setHousingAllowanceType(String value) {
        setAttributeInternal(HOUSINGALLOWANCETYPE, value);
    }

    /**
     * Gets the attribute value for HOUSING_ALLOWANCE_AMOUNT using the alias name HousingAllowanceAmount.
     * @return the HOUSING_ALLOWANCE_AMOUNT
     */
    public Number getHousingAllowanceAmount() {
        return (Number) getAttributeInternal(HOUSINGALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for HOUSING_ALLOWANCE_AMOUNT using the alias name HousingAllowanceAmount.
     * @param value value to set the HOUSING_ALLOWANCE_AMOUNT
     */
    public void setHousingAllowanceAmount(Number value) {
        setAttributeInternal(HOUSINGALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for FOOD_ALLOWANCE_TYPE using the alias name FoodAllowanceType.
     * @return the FOOD_ALLOWANCE_TYPE
     */
    public String getFoodAllowanceType() {
        return (String) getAttributeInternal(FOODALLOWANCETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FOOD_ALLOWANCE_TYPE using the alias name FoodAllowanceType.
     * @param value value to set the FOOD_ALLOWANCE_TYPE
     */
    public void setFoodAllowanceType(String value) {
        setAttributeInternal(FOODALLOWANCETYPE, value);
    }

    /**
     * Gets the attribute value for FOOD_ALLOWANCE_AMOUNT using the alias name FoodAllowanceAmount.
     * @return the FOOD_ALLOWANCE_AMOUNT
     */
    public Number getFoodAllowanceAmount() {
        return (Number) getAttributeInternal(FOODALLOWANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FOOD_ALLOWANCE_AMOUNT using the alias name FoodAllowanceAmount.
     * @param value value to set the FOOD_ALLOWANCE_AMOUNT
     */
    public void setFoodAllowanceAmount(Number value) {
        setAttributeInternal(FOODALLOWANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for MEANS_TRAVEL using the alias name MeansTravel.
     * @return the MEANS_TRAVEL
     */
    public String getMeansTravel() {
        return (String) getAttributeInternal(MEANSTRAVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for MEANS_TRAVEL using the alias name MeansTravel.
     * @param value value to set the MEANS_TRAVEL
     */
    public void setMeansTravel(String value) {
        setAttributeInternal(MEANSTRAVEL, value);
    }

    /**
     * Gets the attribute value for VISA_COST using the alias name VisaCost.
     * @return the VISA_COST
     */
    public Number getVisaCost() {
        return (Number) getAttributeInternal(VISACOST);
    }

    /**
     * Sets <code>value</code> as attribute value for VISA_COST using the alias name VisaCost.
     * @param value value to set the VISA_COST
     */
    public void setVisaCost(Number value) {
        setAttributeInternal(VISACOST, value);
    }

    /**
     * Gets the attribute value for OTHER_COST using the alias name OtherCost.
     * @return the OTHER_COST
     */
    public Number getOtherCost() {
        return (Number) getAttributeInternal(OTHERCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_COST using the alias name OtherCost.
     * @param value value to set the OTHER_COST
     */
    public void setOtherCost(Number value) {
        setAttributeInternal(OTHERCOST, value);
    }

    /**
     * Gets the attribute value for BUDGET_FLAG using the alias name BudgetFlag.
     * @return the BUDGET_FLAG
     */
    public String getBudgetFlag() {
        return (String) getAttributeInternal(BUDGETFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_FLAG using the alias name BudgetFlag.
     * @param value value to set the BUDGET_FLAG
     */
    public void setBudgetFlag(String value) {
        setAttributeInternal(BUDGETFLAG, value);
    }

    /**
     * Gets the attribute value for TRIP_TYPE using the alias name TripType.
     * @return the TRIP_TYPE
     */
    public String getTripType() {
        return (String) getAttributeInternal(TRIPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIP_TYPE using the alias name TripType.
     * @param value value to set the TRIP_TYPE
     */
    public void setTripType(String value) {
        setAttributeInternal(TRIPTYPE, value);
    }

    /**
     * Gets the attribute value for PERSONE_NAME using the alias name PersoneName.
     * @return the PERSONE_NAME
     */
    public String getPersoneName() {
        return (String) getAttributeInternal(PERSONENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSONE_NAME using the alias name PersoneName.
     * @param value value to set the PERSONE_NAME
     */
    public void setPersoneName(String value) {
        setAttributeInternal(PERSONENAME, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for REJECT_COMMENTS using the alias name RejectComments.
     * @return the REJECT_COMMENTS
     */
    public String getRejectComments() {
        return (String) getAttributeInternal(REJECTCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECT_COMMENTS using the alias name RejectComments.
     * @param value value to set the REJECT_COMMENTS
     */
    public void setRejectComments(String value) {
        setAttributeInternal(REJECTCOMMENTS, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE using the alias name Assignee.
     * @return the ASSIGNEE
     */
    public String getAssignee() {
        return (String) getAttributeInternal(ASSIGNEE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE using the alias name Assignee.
     * @param value value to set the ASSIGNEE
     */
    public void setAssignee(String value) {
        setAttributeInternal(ASSIGNEE, value);
    }

    /**
     * Gets the attribute value for TRIP_REASON using the alias name TripReason.
     * @return the TRIP_REASON
     */
    public String getTripReason() {
        return (String) getAttributeInternal(TRIPREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIP_REASON using the alias name TripReason.
     * @param value value to set the TRIP_REASON
     */
    public void setTripReason(String value) {
        setAttributeInternal(TRIPREASON, value);
    }

    /**
     * Gets the attribute value for EVENT_SUBJECT using the alias name EventSubject.
     * @return the EVENT_SUBJECT
     */
    public String getEventSubject() {
        return (String) getAttributeInternal(EVENTSUBJECT);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_SUBJECT using the alias name EventSubject.
     * @param value value to set the EVENT_SUBJECT
     */
    public void setEventSubject(String value) {
        setAttributeInternal(EVENTSUBJECT, value);
    }

    /**
     * Gets the attribute value for EVENT_TYPE using the alias name EventType.
     * @return the EVENT_TYPE
     */
    public String getEventType() {
        return (String) getAttributeInternal(EVENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_TYPE using the alias name EventType.
     * @param value value to set the EVENT_TYPE
     */
    public void setEventType(String value) {
        setAttributeInternal(EVENTTYPE, value);
    }

    /**
     * Gets the attribute value for REQUIRED_VISA using the alias name RequiredVisa.
     * @return the REQUIRED_VISA
     */
    public String getRequiredVisa() {
        return (String) getAttributeInternal(REQUIREDVISA);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUIRED_VISA using the alias name RequiredVisa.
     * @param value value to set the REQUIRED_VISA
     */
    public void setRequiredVisa(String value) {
        setAttributeInternal(REQUIREDVISA, value);
    }

    /**
     * Gets the attribute value for TARGETED_COMPETENCIES using the alias name TargetedCompetencies.
     * @return the TARGETED_COMPETENCIES
     */
    public String getTargetedCompetencies() {
        return (String) getAttributeInternal(TARGETEDCOMPETENCIES);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGETED_COMPETENCIES using the alias name TargetedCompetencies.
     * @param value value to set the TARGETED_COMPETENCIES
     */
    public void setTargetedCompetencies(String value) {
        setAttributeInternal(TARGETEDCOMPETENCIES, value);
    }

    /**
     * Gets the attribute value for COURSE_NAME using the alias name CourseName.
     * @return the COURSE_NAME
     */
    public String getCourseName() {
        return (String) getAttributeInternal(COURSENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COURSE_NAME using the alias name CourseName.
     * @param value value to set the COURSE_NAME
     */
    public void setCourseName(String value) {
        setAttributeInternal(COURSENAME, value);
    }

    /**
     * Gets the attribute value for EXPENSE_BUSINESS_TRIP_ID using the alias name ExpenseBusinessTripId.
     * @return the EXPENSE_BUSINESS_TRIP_ID
     */
    public Number getExpenseBusinessTripId() {
        return (Number) getAttributeInternal(EXPENSEBUSINESSTRIPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENSE_BUSINESS_TRIP_ID using the alias name ExpenseBusinessTripId.
     * @param value value to set the EXPENSE_BUSINESS_TRIP_ID
     */
    public void setExpenseBusinessTripId(Number value) {
        setAttributeInternal(EXPENSEBUSINESSTRIPID, value);
    }

    /**
     * Gets the attribute value for EXPENSE_FLAG using the alias name ExpenseFlag.
     * @return the EXPENSE_FLAG
     */
    public String getExpenseFlag() {
        return (String) getAttributeInternal(EXPENSEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENSE_FLAG using the alias name ExpenseFlag.
     * @param value value to set the EXPENSE_FLAG
     */
    public void setExpenseFlag(String value) {
        setAttributeInternal(EXPENSEFLAG, value);
    }

    /**
     * Gets the attribute value for EXPENSE_TYPE using the alias name ExpenseType.
     * @return the EXPENSE_TYPE
     */
    public String getExpenseType() {
        return (String) getAttributeInternal(EXPENSETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPENSE_TYPE using the alias name ExpenseType.
     * @param value value to set the EXPENSE_TYPE
     */
    public void setExpenseType(String value) {
        setAttributeInternal(EXPENSETYPE, value);
    }

    /**
     * Gets the attribute value for CANCEL_REASON using the alias name CancelReason.
     * @return the CANCEL_REASON
     */
    public String getCancelReason() {
        return (String) getAttributeInternal(CANCELREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_REASON using the alias name CancelReason.
     * @param value value to set the CANCEL_REASON
     */
    public void setCancelReason(String value) {
        setAttributeInternal(CANCELREASON, value);
    }

    /**
     * Gets the attribute value for SUB_TYPE using the alias name SubType.
     * @return the SUB_TYPE
     */
    public String getSubType() {
        return (String) getAttributeInternal(SUBTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_TYPE using the alias name SubType.
     * @param value value to set the SUB_TYPE
     */
    public void setSubType(String value) {
        setAttributeInternal(SUBTYPE, value);
    }

    /**
     * Gets the attribute value for NEW_CITY using the alias name NewCity.
     * @return the NEW_CITY
     */
    public String getNewCity() {
        return (String) getAttributeInternal(NEWCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_CITY using the alias name NewCity.
     * @param value value to set the NEW_CITY
     */
    public void setNewCity(String value) {
        setAttributeInternal(NEWCITY, value);
    }

    /**
     * Gets the attribute value for DESTINATION_TYPE using the alias name DestinationType.
     * @return the DESTINATION_TYPE
     */
    public String getDestinationType() {
        return (String) getAttributeInternal(DESTINATIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_TYPE using the alias name DestinationType.
     * @param value value to set the DESTINATION_TYPE
     */
    public void setDestinationType(String value) {
        setAttributeInternal(DESTINATIONTYPE, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for COST_CENTER using the alias name CostCenter.
     * @return the COST_CENTER
     */
    public String getCostCenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER using the alias name CostCenter.
     * @param value value to set the COST_CENTER
     */
    public void setCostCenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for COST_CENTER_NUMBER using the alias name CostCenterNumber.
     * @return the COST_CENTER_NUMBER
     */
    public String getCostCenterNumber() {
        return (String) getAttributeInternal(COSTCENTERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER_NUMBER using the alias name CostCenterNumber.
     * @param value value to set the COST_CENTER_NUMBER
     */
    public void setCostCenterNumber(String value) {
        setAttributeInternal(COSTCENTERNUMBER, value);
    }

    /**
     * Gets the attribute value for TRAINING_COST using the alias name TrainingCost.
     * @return the TRAINING_COST
     */
    public Number getTrainingCost() {
        return (Number) getAttributeInternal(TRAININGCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAINING_COST using the alias name TrainingCost.
     * @param value value to set the TRAINING_COST
     */
    public void setTrainingCost(Number value) {
        setAttributeInternal(TRAININGCOST, value);
    }

    /**
     * Gets the attribute value for OTHER_MEANS_TRAVEL using the alias name OtherMeansTravel.
     * @return the OTHER_MEANS_TRAVEL
     */
    public String getOtherMeansTravel() {
        return (String) getAttributeInternal(OTHERMEANSTRAVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_MEANS_TRAVEL using the alias name OtherMeansTravel.
     * @param value value to set the OTHER_MEANS_TRAVEL
     */
    public void setOtherMeansTravel(String value) {
        setAttributeInternal(OTHERMEANSTRAVEL, value);
    }

    /**
     * Gets the attribute value for TRAVEL_COST using the alias name TravelCost.
     * @return the TRAVEL_COST
     */
    public Number getTravelCost() {
        return (Number) getAttributeInternal(TRAVELCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAVEL_COST using the alias name TravelCost.
     * @param value value to set the TRAVEL_COST
     */
    public void setTravelCost(Number value) {
        setAttributeInternal(TRAVELCOST, value);
    }

    /**
     * Gets the attribute value for EVENT_COST using the alias name EventCost.
     * @return the EVENT_COST
     */
    public Number getEventCost() {
        return (Number) getAttributeInternal(EVENTCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_COST using the alias name EventCost.
     * @param value value to set the EVENT_COST
     */
    public void setEventCost(Number value) {
        setAttributeInternal(EVENTCOST, value);
    }

    /**
     * Gets the attribute value for TRIP_COMMENT using the alias name TripComment.
     * @return the TRIP_COMMENT
     */
    public String getTripComment() {
        return (String) getAttributeInternal(TRIPCOMMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIP_COMMENT using the alias name TripComment.
     * @param value value to set the TRIP_COMMENT
     */
    public void setTripComment(String value) {
        setAttributeInternal(TRIPCOMMENT, value);
    }

    /**
     * Gets the attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @return the PERSON_POSITION
     */
    public String getPersonPosition() {
        return (String) getAttributeInternal(PERSONPOSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @param value value to set the PERSON_POSITION
     */
    public void setPersonPosition(String value) {
        setAttributeInternal(PERSONPOSITION, value);
    }

    /**
     * Gets the attribute value for PERSON_JOB using the alias name PersonJob.
     * @return the PERSON_JOB
     */
    public String getPersonJob() {
        return (String) getAttributeInternal(PERSONJOB);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_JOB using the alias name PersonJob.
     * @param value value to set the PERSON_JOB
     */
    public void setPersonJob(String value) {
        setAttributeInternal(PERSONJOB, value);
    }

    /**
     * Gets the attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @return the PERSON_DEPARTMENT
     */
    public String getPersonDepartment() {
        return (String) getAttributeInternal(PERSONDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @param value value to set the PERSON_DEPARTMENT
     */
    public void setPersonDepartment(String value) {
        setAttributeInternal(PERSONDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @return the PERSON_LOCATION
     */
    public String getPersonLocation() {
        return (String) getAttributeInternal(PERSONLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @param value value to set the PERSON_LOCATION
     */
    public void setPersonLocation(String value) {
        setAttributeInternal(PERSONLOCATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OtherCities.
     * @return the OtherCities
     */
    public String getOtherCities() {
        return (String) getAttributeInternal(OTHERCITIES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OtherCities.
     * @param value value to set the  OtherCities
     */
    public void setOtherCities(String value) {
        setAttributeInternal(OTHERCITIES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalAmount.
     * @return the TotalAmount
     */
    public Number getTotalAmount() {
        return (Number) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalAmount.
     * @param value value to set the  TotalAmount
     */
    public void setTotalAmount(Number value) {
        setAttributeInternal(TOTALAMOUNT, value);
        setTotalBtCost(value);
    }

    /**
     * Gets the attribute value for the calculated attribute StepComment.
     * @return the StepComment
     */
    public String getStepComment() {
        return (String) getAttributeInternal(STEPCOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StepComment.
     * @param value value to set the  StepComment
     */
    public void setStepComment(String value) {
        setAttributeInternal(STEPCOMMENT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute attachmentRowCount.
     * @return the attachmentRowCount
     */
    public String getattachmentRowCount() {
        return (String) getAttributeInternal(ATTACHMENTROWCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute attachmentRowCount.
     * @param value value to set the  attachmentRowCount
     */
    public void setattachmentRowCount(String value) {
        setAttributeInternal(ATTACHMENTROWCOUNT, value);
    }

    /**
     * Gets the attribute value for LOB using the alias name Lob.
     * @return the LOB
     */
    public String getLob() {
        return (String) getAttributeInternal(LOB);
    }

    /**
     * Sets <code>value</code> as attribute value for LOB using the alias name Lob.
     * @param value value to set the LOB
     */
    public void setLob(String value) {
        setAttributeInternal(LOB, value);
    }

    /**
     * Gets the attribute value for DIVISION using the alias name Division.
     * @return the DIVISION
     */
    public String getDivision() {
        return (String) getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
     * @param value value to set the DIVISION
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute destinationTypeTrans.
     * @return the destinationTypeTrans
     */
    public String getdestinationTypeTrans() {
        return (String) getAttributeInternal(DESTINATIONTYPETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute destinationTypeTrans.
     * @param value value to set the  destinationTypeTrans
     */
    public void setdestinationTypeTrans(String value) {
        setAttributeInternal(DESTINATIONTYPETRANS, value);
    }
	
	/**
     * Gets the attribute value for the calculated attribute MoreCities.
     * @return the MoreCities
     */
    public Boolean getMoreCities() {
        return (Boolean) getAttributeInternal(MORECITIES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MoreCities.
     * @param value value to set the  MoreCities
     */
    public void setMoreCities(Boolean value) {
        setAttributeInternal(MORECITIES, value);
    }

    /**
     * Gets the attribute value for ONE_WAY_TRIP using the alias name OneWayTrip.
     * @return the ONE_WAY_TRIP
     */
    public String getOneWayTrip() {
        return (String) getAttributeInternal(ONEWAYTRIP);
    }

    /**
     * Sets <code>value</code> as attribute value for ONE_WAY_TRIP using the alias name OneWayTrip.
     * @param value value to set the ONE_WAY_TRIP
     */
    public void setOneWayTrip(String value) {
        setAttributeInternal(ONEWAYTRIP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_OneWay.
     * @return the Trans_OneWay
     */
    
    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_OneWay.
     * @param value value to set the  Trans_OneWay
     */


    /**
     * Gets the attribute value for the calculated attribute OneWay_TRANS.
     * @return the OneWay_TRANS
     */
    public Boolean getOneWay_TRANS() {
        if(this.getOneWayTrip()!=null &&this.getOneWayTrip().equals("Y")) {
            return true;
        }
        else {
            return false;
        }
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OneWay_TRANS.
     * @param value value to set the  OneWay_TRANS
     */
    public void setOneWay_TRANS(Boolean value) {
        if(value) {
            this.setOneWayTrip("Y");
        }
        else {
            this.setOneWayTrip("N");
        }
    }

    /**
     * Gets the attribute value for MORE_CITIES_CHECK using the alias name MoreCitiesCheck.
     * @return the MORE_CITIES_CHECK
     */
    public String getMoreCitiesCheck() {
        return (String) getAttributeInternal(MORECITIESCHECK);
    }

    /**
     * Sets <code>value</code> as attribute value for MORE_CITIES_CHECK using the alias name MoreCitiesCheck.
     * @param value value to set the MORE_CITIES_CHECK
     */
    public void setMoreCitiesCheck(String value) {
        setAttributeInternal(MORECITIESCHECK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute More_Cities_Check_Trans.
     * @return the More_Cities_Check_Trans
     */
    public Boolean getMore_Cities_Check_Trans() {
        if(this.getMoreCitiesCheck()!=null &&this.getMoreCitiesCheck().equals("Y")) {
                    return true;
                }
                else {
                    return false;
                }
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute More_Cities_Check_Trans.
     * @param value value to set the  More_Cities_Check_Trans
     */
    public void setMore_Cities_Check_Trans(Boolean value) {
        if(value) {
                    this.setMoreCitiesCheck("Y");
                }
                else {
                    this.setMoreCitiesCheck("N");
                }
      
    }

    /**
     * Gets the attribute value for OTHER_CITIES_TRANS using the alias name OtherCitiesTrans.
     * @return the OTHER_CITIES_TRANS
     */
    public String getOtherCitiesTrans() {
        return (String) getAttributeInternal(OTHERCITIESTRANS);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_CITIES_TRANS using the alias name OtherCitiesTrans.
     * @param value value to set the OTHER_CITIES_TRANS
     */
    public void setOtherCitiesTrans(String value) {
        setAttributeInternal(OTHERCITIESTRANS, value);
    }

    /**
     * Gets the attribute value for EDIT_REQUEST using the alias name EditRequest.
     * @return the EDIT_REQUEST
     */
    public String getEditRequest() {
        return (String) getAttributeInternal(EDITREQUEST);
    }

    /**
     * Sets <code>value</code> as attribute value for EDIT_REQUEST using the alias name EditRequest.
     * @param value value to set the EDIT_REQUEST
     */
    public void setEditRequest(String value) {
        setAttributeInternal(EDITREQUEST, value);
    }

    /**
     * Gets the attribute value for OTHER_BY_EMPLOYEE using the alias name OtherByEmployee.
     * @return the OTHER_BY_EMPLOYEE
     */
    public Number getOtherByEmployee() {
        return (Number) getAttributeInternal(OTHERBYEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_BY_EMPLOYEE using the alias name OtherByEmployee.
     * @param value value to set the OTHER_BY_EMPLOYEE
     */
    public void setOtherByEmployee(Number value) {
        setAttributeInternal(OTHERBYEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for OTHER_BY_TATWEER using the alias name OtherByTatweer.
     * @return the OTHER_BY_TATWEER
     */
    public Number getOtherByTatweer() {
        return (Number) getAttributeInternal(OTHERBYTATWEER);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_BY_TATWEER using the alias name OtherByTatweer.
     * @param value value to set the OTHER_BY_TATWEER
     */
    public void setOtherByTatweer(Number value) {
        setAttributeInternal(OTHERBYTATWEER, value);
    }

    /**
     * Gets the attribute value for TRAINING_BY_EMPLOYEE using the alias name TrainingByEmployee.
     * @return the TRAINING_BY_EMPLOYEE
     */
    public Number getTrainingByEmployee() {
        return (Number) getAttributeInternal(TRAININGBYEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAINING_BY_EMPLOYEE using the alias name TrainingByEmployee.
     * @param value value to set the TRAINING_BY_EMPLOYEE
     */
    public void setTrainingByEmployee(Number value) {
        setAttributeInternal(TRAININGBYEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for TRAVEL_COST_BY_EMPLOYEE using the alias name TravelCostByEmployee.
     * @return the TRAVEL_COST_BY_EMPLOYEE
     */
    public Number getTravelCostByEmployee() {
        return (Number) getAttributeInternal(TRAVELCOSTBYEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAVEL_COST_BY_EMPLOYEE using the alias name TravelCostByEmployee.
     * @param value value to set the TRAVEL_COST_BY_EMPLOYEE
     */
    public void setTravelCostByEmployee(Number value) {
        setAttributeInternal(TRAVELCOSTBYEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for DECLARATION using the alias name Declaration.
     * @return the DECLARATION
     */
    public String getDeclaration() {
        return (String) getAttributeInternal(DECLARATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DECLARATION using the alias name Declaration.
     * @param value value to set the DECLARATION
     */
    public void setDeclaration(String value) {
        setAttributeInternal(DECLARATION, value);
    }

    /**
     * Gets the attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @return the INVOICE_NUMBER
     */
    public String getInvoiceNumber() {
        return (String) getAttributeInternal(INVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NUMBER using the alias name InvoiceNumber.
     * @param value value to set the INVOICE_NUMBER
     */
    public void setInvoiceNumber(String value) {
        setAttributeInternal(INVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for TOTAL_BT_COST using the alias name TotalBtCost.
     * @return the TOTAL_BT_COST
     */
    public Number getTotalBtCost() {
        return (Number) getAttributeInternal(TOTALBTCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_BT_COST using the alias name TotalBtCost.
     * @param value value to set the TOTAL_BT_COST
     */
    public void setTotalBtCost(Number value) {
        setAttributeInternal(TOTALBTCOST, value);
    }

    /**
     * Gets the attribute value for PAYMENT_STATUS using the alias name PaymentStatus.
     * @return the PAYMENT_STATUS
     */
    public String getPaymentStatus() {
        return (String) getAttributeInternal(PAYMENTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_STATUS using the alias name PaymentStatus.
     * @param value value to set the PAYMENT_STATUS
     */
    public void setPaymentStatus(String value) {
        setAttributeInternal(PAYMENTSTATUS, value);
    }

    /**
     * Gets the attribute value for PREFERRED_ARRIVAL_TIME using the alias name PreferredArrivalTime.
     * @return the PREFERRED_ARRIVAL_TIME
     */
    public Timestamp getPreferredArrivalTime() {
        return (Timestamp) getAttributeInternal(PREFERREDARRIVALTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for PREFERRED_ARRIVAL_TIME using the alias name PreferredArrivalTime.
     * @param value value to set the PREFERRED_ARRIVAL_TIME
     */
    public void setPreferredArrivalTime(Timestamp value) {
        setAttributeInternal(PREFERREDARRIVALTIME, value);
    }

    /**
     * Gets the attribute value for PREFERRED_DEPARTURE_TIME using the alias name PreferredDepartureTime.
     * @return the PREFERRED_DEPARTURE_TIME
     */
    public Timestamp getPreferredDepartureTime() {
        return (Timestamp) getAttributeInternal(PREFERREDDEPARTURETIME);
    }

    /**
     * Sets <code>value</code> as attribute value for PREFERRED_DEPARTURE_TIME using the alias name PreferredDepartureTime.
     * @param value value to set the PREFERRED_DEPARTURE_TIME
     */
    public void setPreferredDepartureTime(Timestamp value) {
        setAttributeInternal(PREFERREDDEPARTURETIME, value);
    }

    /**
     * Gets the attribute value for ACTUAL_END_DATE using the alias name ActualEndDate.
     * @return the ACTUAL_END_DATE
     */
    public Date getActualEndDate() {
        return (Date) getAttributeInternal(ACTUALENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_END_DATE using the alias name ActualEndDate.
     * @param value value to set the ACTUAL_END_DATE
     */
    public void setActualEndDate(Date value) {
        setAttributeInternal(ACTUALENDDATE, value);
    }

    /**
     * Gets the attribute value for ACTUAL_START_DATE using the alias name ActualStartDate.
     * @return the ACTUAL_START_DATE
     */
    public Date getActualStartDate() {
        return (Date) getAttributeInternal(ACTUALSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_START_DATE using the alias name ActualStartDate.
     * @param value value to set the ACTUAL_START_DATE
     */
    public void setActualStartDate(Date value) {
        setAttributeInternal(ACTUALSTARTDATE, value);
    }

    /**
     * Gets the attribute value for TO_CITY using the alias name ToCity.
     * @return the TO_CITY
     */
    public String getToCity() {
        return (String) getAttributeInternal(TOCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_CITY using the alias name ToCity.
     * @param value value to set the TO_CITY
     */
    public void setToCity(String value) {
        setAttributeInternal(TOCITY, value);
    }

    /**
     * Gets the attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @return the ACTION_TAKEN
     */
    public String getActionTaken() {
        return (String) getAttributeInternal(ACTIONTAKEN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @param value value to set the ACTION_TAKEN
     */
    public void setActionTaken(String value) {
        setAttributeInternal(ACTIONTAKEN, value);
    }

    /**
     * Gets the attribute value for TOTAL_FOR_INVOICE using the alias name TotalForInvoice.
     * @return the TOTAL_FOR_INVOICE
     */
    public Number getTotalForInvoice() {
        return (Number) getAttributeInternal(TOTALFORINVOICE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_FOR_INVOICE using the alias name TotalForInvoice.
     * @param value value to set the TOTAL_FOR_INVOICE
     */
    public void setTotalForInvoice(Number value) {
        setAttributeInternal(TOTALFORINVOICE, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @return the ASSIGNEE_NAME
     */
    public String getAssigneeName() {
        return (String) getAttributeInternal(ASSIGNEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @param value value to set the ASSIGNEE_NAME
     */
    public void setAssigneeName(String value) {
        setAttributeInternal(ASSIGNEENAME, value);
    }

    /**
     * Gets the attribute value for BENEFIT_TYPE using the alias name BenefitType.
     * @return the BENEFIT_TYPE
     */
    public String getBenefitType() {
        return (String) getAttributeInternal(BENEFITTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BENEFIT_TYPE using the alias name BenefitType.
     * @param value value to set the BENEFIT_TYPE
     */
    public void setBenefitType(String value) {
        setAttributeInternal(BENEFITTYPE, value);
    }

    /**
     * Gets the attribute value for PER_DIEM_AMOUNT using the alias name PerDiemAmount.
     * @return the PER_DIEM_AMOUNT
     */
    public Number getPerDiemAmount() {
        return (Number) getAttributeInternal(PERDIEMAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for PER_DIEM_AMOUNT using the alias name PerDiemAmount.
     * @param value value to set the PER_DIEM_AMOUNT
     */
    public void setPerDiemAmount(Number value) {
        setAttributeInternal(PERDIEMAMOUNT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RequestAttachmentsView.
     */
    public RowIterator getRequestAttachmentsView() {
        return (RowIterator)getAttributeInternal(REQUESTATTACHMENTSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ApprovalHistoryVO.
     */
    public RowIterator getApprovalHistoryVO() {
        return (RowIterator)getAttributeInternal(APPROVALHISTORYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TripTypeStaticView.
     */
    public RowSet getTripTypeStaticView() {
        return (RowSet)getAttributeInternal(TRIPTYPESTATICVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountriesLOV.
     */
    public RowSet getCountriesLOV() {
        return (RowSet)getAttributeInternal(COUNTRIESLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CitiesLOV.
     */
    public RowSet getCitiesLOV() {
        return (RowSet)getAttributeInternal(CITIESLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AllowanceTypeStaticView.
     */
    public RowSet getAllowanceTypeStaticView() {
        return (RowSet)getAttributeInternal(ALLOWANCETYPESTATICVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RequestStepsROView.
     */
    public RowSet getRequestStepsROView() {
        return (RowSet)getAttributeInternal(REQUESTSTEPSROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BusinessTripExpenseROView.
     */
    public RowSet getBusinessTripExpenseROView() {
        return (RowSet)getAttributeInternal(BUSINESSTRIPEXPENSEROVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EventTypeStaticView.
     */
    public RowSet getEventTypeStaticView() {
        return (RowSet)getAttributeInternal(EVENTTYPESTATICVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BusinessTripSubTypeStaticView1.
     */
    public RowSet getBusinessTripSubTypeStaticView1() {
        return (RowSet)getAttributeInternal(BUSINESSTRIPSUBTYPESTATICVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DestinationStaticView1.
     */
    public RowSet getDestinationStaticView1() {
        return (RowSet)getAttributeInternal(DESTINATIONSTATICVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartmentsLOV1.
     */
    public RowSet getDepartmentsLOV1() {
        return (RowSet)getAttributeInternal(DEPARTMENTSLOV1);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
