package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 13:00:36 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptEmployeesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PersonId {
            public Object get(DeptEmployeesVORowImpl obj) {
                return obj.getPersonId();
            }

            public void put(DeptEmployeesVORowImpl obj, Object value) {
                obj.setPersonId((String)value);
            }
        }
        ,
        PersonNumber {
            public Object get(DeptEmployeesVORowImpl obj) {
                return obj.getPersonNumber();
            }

            public void put(DeptEmployeesVORowImpl obj, Object value) {
                obj.setPersonNumber((String)value);
            }
        }
        ,
        DisplayName {
            public Object get(DeptEmployeesVORowImpl obj) {
                return obj.getDisplayName();
            }

            public void put(DeptEmployeesVORowImpl obj, Object value) {
                obj.setDisplayName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DeptEmployeesVORowImpl object);

        public abstract void put(DeptEmployeesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DeptEmployeesVORowImpl() {
    }

    /**
     * Gets DeptEmployeesEO entity object.
     * @return the DeptEmployeesEO
     */
    public EntityImpl getDeptEmployeesEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public String getPersonId() {
        return (String) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(String value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @return the PERSON_NUMBER
     */
    public String getPersonNumber() {
        return (String) getAttributeInternal(PERSONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @param value value to set the PERSON_NUMBER
     */
    public void setPersonNumber(String value) {
        setAttributeInternal(PERSONNUMBER, value);
    }

    /**
     * Gets the attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @return the DISPLAY_NAME
     */
    public String getDisplayName() {
        return (String) getAttributeInternal(DISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @param value value to set the DISPLAY_NAME
     */
    public void setDisplayName(String value) {
        setAttributeInternal(DISPLAYNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
