package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 22 10:20:42 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ElementAccountVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ElementAccountVOImpl() {
    }

    /**
     * Returns the bind variable value for bvElementName.
     * @return bind variable value for bvElementName
     */
    public String getbvElementName() {
        return (String)getNamedWhereClauseParam("bvElementName");
    }

    /**
     * Sets <code>value</code> for bind variable bvElementName.
     * @param value value to bind as bvElementName
     */
    public void setbvElementName(String value) {
        setNamedWhereClauseParam("bvElementName", value);
    }
}
