package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 12 02:06:00 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExitReEntryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExitReEntryVOImpl() {
    }

    /**
     * Returns the variable value for bindPersonNumber.
     * @return variable value for bindPersonNumber
     */
    public String getbindPersonNumber() {
        return (String)ensureVariableManager().getVariableValue("bindPersonNumber");
    }

    /**
     * Sets <code>value</code> for variable bindPersonNumber.
     * @param value value to bind as bindPersonNumber
     */
    public void setbindPersonNumber(String value) {
        ensureVariableManager().setVariableValue("bindPersonNumber", value);
    }

    /**
     * Returns the variable value for bindAssignee.
     * @return variable value for bindAssignee
     */
    public String getbindAssignee() {
        return (String)ensureVariableManager().getVariableValue("bindAssignee");
    }

    /**
     * Sets <code>value</code> for variable bindAssignee.
     * @param value value to bind as bindAssignee
     */
    public void setbindAssignee(String value) {
        ensureVariableManager().setVariableValue("bindAssignee", value);
    }

    /**
     * Returns the variable value for bindAssignee2.
     * @return variable value for bindAssignee2
     */
    public String getbindAssignee2() {
        return (String)ensureVariableManager().getVariableValue("bindAssignee2");
    }

    /**
     * Sets <code>value</code> for variable bindAssignee2.
     * @param value value to bind as bindAssignee2
     */
    public void setbindAssignee2(String value) {
        ensureVariableManager().setVariableValue("bindAssignee2", value);
    }
}
