package com.sbm.selfServices.model.views.up;

import com.sbm.selfServices.model.entities.LoanSettlement_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 06 16:56:37 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LoanSettlement_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActionTaken {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getActionTaken();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setActionTaken((String)value);
            }
        }
        ,
        Assignee {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getAssignee();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setAssignee((String)value);
            }
        }
        ,
        AssigneeName {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getAssigneeName();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setAssigneeName((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedOn {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getCreatedOn();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setCreatedOn((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedOn {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLastUpdatedOn();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLastUpdatedOn((Date)value);
            }
        }
        ,
        LoanCreationDate {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanCreationDate();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanCreationDate((Date)value);
            }
        }
        ,
        LoanDivision {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanDivision();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanDivision((Number)value);
            }
        }
        ,
        LoanId {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanId();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanId((Number)value);
            }
        }
        ,
        LoanNoOfMonths {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanNoOfMonths();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanNoOfMonths((Number)value);
            }
        }
        ,
        LoanPreclosureId {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanPreclosureId();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanPreclosureId((DBSequence)value);
            }
        }
        ,
        LoanRemainingAmount {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanRemainingAmount();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanRemainingAmount((Number)value);
            }
        }
        ,
        LoanTotalAmount {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getLoanTotalAmount();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setLoanTotalAmount((Number)value);
            }
        }
        ,
        PersonDepartment {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonDepartment();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonDepartment((String)value);
            }
        }
        ,
        PersonGrade {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonGrade();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonGrade((String)value);
            }
        }
        ,
        PersonJob {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonJob();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonJob((String)value);
            }
        }
        ,
        PersonLocation {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonLocation();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonLocation((String)value);
            }
        }
        ,
        PersonName {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonName();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonName((String)value);
            }
        }
        ,
        PersonNumber {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonNumber();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonNumber((String)value);
            }
        }
        ,
        PersonPosition {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getPersonPosition();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setPersonPosition((String)value);
            }
        }
        ,
        RejectComment {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getRejectComment();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setRejectComment((String)value);
            }
        }
        ,
        RequestStatus {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        RowID {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getRowID();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        StepId {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getStepId();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setStepId((Long)value);
            }
        }
        ,
        RequestNameTrans {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getRequestNameTrans();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setRequestNameTrans((String)value);
            }
        }
        ,
        AttachmentFile {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getAttachmentFile();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setAttachmentFile((BlobDomain)value);
            }
        }
        ,
        FileName {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getFileName();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        FileType {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getFileType();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setFileType((String)value);
            }
        }
        ,
        ApprovalHistoryVO {
            public Object get(LoanSettlement_VORowImpl obj) {
                return obj.getApprovalHistoryVO();
            }

            public void put(LoanSettlement_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LoanSettlement_VORowImpl object);

        public abstract void put(LoanSettlement_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ACTIONTAKEN = AttributesEnum.ActionTaken.index();
    public static final int ASSIGNEE = AttributesEnum.Assignee.index();
    public static final int ASSIGNEENAME = AttributesEnum.AssigneeName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDON = AttributesEnum.LastUpdatedOn.index();
    public static final int LOANCREATIONDATE = AttributesEnum.LoanCreationDate.index();
    public static final int LOANDIVISION = AttributesEnum.LoanDivision.index();
    public static final int LOANID = AttributesEnum.LoanId.index();
    public static final int LOANNOOFMONTHS = AttributesEnum.LoanNoOfMonths.index();
    public static final int LOANPRECLOSUREID = AttributesEnum.LoanPreclosureId.index();
    public static final int LOANREMAININGAMOUNT = AttributesEnum.LoanRemainingAmount.index();
    public static final int LOANTOTALAMOUNT = AttributesEnum.LoanTotalAmount.index();
    public static final int PERSONDEPARTMENT = AttributesEnum.PersonDepartment.index();
    public static final int PERSONGRADE = AttributesEnum.PersonGrade.index();
    public static final int PERSONJOB = AttributesEnum.PersonJob.index();
    public static final int PERSONLOCATION = AttributesEnum.PersonLocation.index();
    public static final int PERSONNAME = AttributesEnum.PersonName.index();
    public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
    public static final int PERSONPOSITION = AttributesEnum.PersonPosition.index();
    public static final int REJECTCOMMENT = AttributesEnum.RejectComment.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int REQUESTNAMETRANS = AttributesEnum.RequestNameTrans.index();
    public static final int ATTACHMENTFILE = AttributesEnum.AttachmentFile.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int FILETYPE = AttributesEnum.FileType.index();
    public static final int APPROVALHISTORYVO = AttributesEnum.ApprovalHistoryVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LoanSettlement_VORowImpl() {
    }

    /**
     * Gets LoanSettlement_EO entity object.
     * @return the LoanSettlement_EO
     */
    public LoanSettlement_EOImpl getLoanSettlement_EO() {
        return (LoanSettlement_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @return the ACTION_TAKEN
     */
    public String getActionTaken() {
        return (String) getAttributeInternal(ACTIONTAKEN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @param value value to set the ACTION_TAKEN
     */
    public void setActionTaken(String value) {
        setAttributeInternal(ACTIONTAKEN, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE using the alias name Assignee.
     * @return the ASSIGNEE
     */
    public String getAssignee() {
        return (String) getAttributeInternal(ASSIGNEE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE using the alias name Assignee.
     * @param value value to set the ASSIGNEE
     */
    public void setAssignee(String value) {
        setAttributeInternal(ASSIGNEE, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @return the ASSIGNEE_NAME
     */
    public String getAssigneeName() {
        return (String) getAttributeInternal(ASSIGNEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @param value value to set the ASSIGNEE_NAME
     */
    public void setAssigneeName(String value) {
        setAttributeInternal(ASSIGNEENAME, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_ON using the alias name CreatedOn.
     * @return the CREATED_ON
     */
    public Date getCreatedOn() {
        return (Date) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_ON using the alias name CreatedOn.
     * @param value value to set the CREATED_ON
     */
    public void setCreatedOn(Date value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_ON using the alias name LastUpdatedOn.
     * @return the LAST_UPDATED_ON
     */
    public Date getLastUpdatedOn() {
        return (Date) getAttributeInternal(LASTUPDATEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_ON using the alias name LastUpdatedOn.
     * @param value value to set the LAST_UPDATED_ON
     */
    public void setLastUpdatedOn(Date value) {
        setAttributeInternal(LASTUPDATEDON, value);
    }

    /**
     * Gets the attribute value for LOAN_CREATION_DATE using the alias name LoanCreationDate.
     * @return the LOAN_CREATION_DATE
     */
    public Date getLoanCreationDate() {
        return (Date) getAttributeInternal(LOANCREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_CREATION_DATE using the alias name LoanCreationDate.
     * @param value value to set the LOAN_CREATION_DATE
     */
    public void setLoanCreationDate(Date value) {
        setAttributeInternal(LOANCREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LOAN_DIVISION using the alias name LoanDivision.
     * @return the LOAN_DIVISION
     */
    public Number getLoanDivision() {
        return (Number) getAttributeInternal(LOANDIVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_DIVISION using the alias name LoanDivision.
     * @param value value to set the LOAN_DIVISION
     */
    public void setLoanDivision(Number value) {
        setAttributeInternal(LOANDIVISION, value);
    }

    /**
     * Gets the attribute value for LOAN_ID using the alias name LoanId.
     * @return the LOAN_ID
     */
    public Number getLoanId() {
        return (Number) getAttributeInternal(LOANID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_ID using the alias name LoanId.
     * @param value value to set the LOAN_ID
     */
    public void setLoanId(Number value) {
        setAttributeInternal(LOANID, value);
    }

    /**
     * Gets the attribute value for LOAN_NO_OF_MONTHS using the alias name LoanNoOfMonths.
     * @return the LOAN_NO_OF_MONTHS
     */
    public Number getLoanNoOfMonths() {
        return (Number) getAttributeInternal(LOANNOOFMONTHS);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_NO_OF_MONTHS using the alias name LoanNoOfMonths.
     * @param value value to set the LOAN_NO_OF_MONTHS
     */
    public void setLoanNoOfMonths(Number value) {
        setAttributeInternal(LOANNOOFMONTHS, value);
    }

    /**
     * Gets the attribute value for LOAN_PRECLOSURE_ID using the alias name LoanPreclosureId.
     * @return the LOAN_PRECLOSURE_ID
     */
    public DBSequence getLoanPreclosureId() {
        return (DBSequence)getAttributeInternal(LOANPRECLOSUREID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_PRECLOSURE_ID using the alias name LoanPreclosureId.
     * @param value value to set the LOAN_PRECLOSURE_ID
     */
    public void setLoanPreclosureId(DBSequence value) {
        setAttributeInternal(LOANPRECLOSUREID, value);
    }

    /**
     * Gets the attribute value for LOAN_REMAINING_AMOUNT using the alias name LoanRemainingAmount.
     * @return the LOAN_REMAINING_AMOUNT
     */
    public Number getLoanRemainingAmount() {
        return (Number) getAttributeInternal(LOANREMAININGAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_REMAINING_AMOUNT using the alias name LoanRemainingAmount.
     * @param value value to set the LOAN_REMAINING_AMOUNT
     */
    public void setLoanRemainingAmount(Number value) {
        setAttributeInternal(LOANREMAININGAMOUNT, value);
    }

    /**
     * Gets the attribute value for LOAN_TOTAL_AMOUNT using the alias name LoanTotalAmount.
     * @return the LOAN_TOTAL_AMOUNT
     */
    public Number getLoanTotalAmount() {
        return (Number) getAttributeInternal(LOANTOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for LOAN_TOTAL_AMOUNT using the alias name LoanTotalAmount.
     * @param value value to set the LOAN_TOTAL_AMOUNT
     */
    public void setLoanTotalAmount(Number value) {
        setAttributeInternal(LOANTOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @return the PERSON_DEPARTMENT
     */
    public String getPersonDepartment() {
        return (String) getAttributeInternal(PERSONDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @param value value to set the PERSON_DEPARTMENT
     */
    public void setPersonDepartment(String value) {
        setAttributeInternal(PERSONDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for PERSON_GRADE using the alias name PersonGrade.
     * @return the PERSON_GRADE
     */
    public String getPersonGrade() {
        return (String) getAttributeInternal(PERSONGRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_GRADE using the alias name PersonGrade.
     * @param value value to set the PERSON_GRADE
     */
    public void setPersonGrade(String value) {
        setAttributeInternal(PERSONGRADE, value);
    }

    /**
     * Gets the attribute value for PERSON_JOB using the alias name PersonJob.
     * @return the PERSON_JOB
     */
    public String getPersonJob() {
        return (String) getAttributeInternal(PERSONJOB);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_JOB using the alias name PersonJob.
     * @param value value to set the PERSON_JOB
     */
    public void setPersonJob(String value) {
        setAttributeInternal(PERSONJOB, value);
    }

    /**
     * Gets the attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @return the PERSON_LOCATION
     */
    public String getPersonLocation() {
        return (String) getAttributeInternal(PERSONLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @param value value to set the PERSON_LOCATION
     */
    public void setPersonLocation(String value) {
        setAttributeInternal(PERSONLOCATION, value);
    }

    /**
     * Gets the attribute value for PERSON_NAME using the alias name PersonName.
     * @return the PERSON_NAME
     */
    public String getPersonName() {
        return (String) getAttributeInternal(PERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NAME using the alias name PersonName.
     * @param value value to set the PERSON_NAME
     */
    public void setPersonName(String value) {
        setAttributeInternal(PERSONNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @return the PERSON_NUMBER
     */
    public String getPersonNumber() {
        return (String) getAttributeInternal(PERSONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @param value value to set the PERSON_NUMBER
     */
    public void setPersonNumber(String value) {
        setAttributeInternal(PERSONNUMBER, value);
    }

    /**
     * Gets the attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @return the PERSON_POSITION
     */
    public String getPersonPosition() {
        return (String) getAttributeInternal(PERSONPOSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @param value value to set the PERSON_POSITION
     */
    public void setPersonPosition(String value) {
        setAttributeInternal(PERSONPOSITION, value);
    }

    /**
     * Gets the attribute value for REJECT_COMMENT using the alias name RejectComment.
     * @return the REJECT_COMMENT
     */
    public String getRejectComment() {
        return (String) getAttributeInternal(REJECTCOMMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECT_COMMENT using the alias name RejectComment.
     * @param value value to set the REJECT_COMMENT
     */
    public void setRejectComment(String value) {
        setAttributeInternal(REJECTCOMMENT, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for STEP_ID using the alias name StepId.
     * @return the STEP_ID
     */
    public Long getStepId() {
        return (Long) getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as attribute value for STEP_ID using the alias name StepId.
     * @param value value to set the STEP_ID
     */
    public void setStepId(Long value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequestNameTrans.
     * @return the RequestNameTrans
     */
    public String getRequestNameTrans() {
        return (String) getAttributeInternal(REQUESTNAMETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequestNameTrans.
     * @param value value to set the  RequestNameTrans
     */
    public void setRequestNameTrans(String value) {
        setAttributeInternal(REQUESTNAMETRANS, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT_FILE using the alias name AttachmentFile.
     * @return the ATTACHMENT_FILE
     */
    public BlobDomain getAttachmentFile() {
        return (BlobDomain) getAttributeInternal(ATTACHMENTFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT_FILE using the alias name AttachmentFile.
     * @param value value to set the ATTACHMENT_FILE
     */
    public void setAttachmentFile(BlobDomain value) {
        setAttributeInternal(ATTACHMENTFILE, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for FILE_TYPE using the alias name FileType.
     * @return the FILE_TYPE
     */
    public String getFileType() {
        return (String) getAttributeInternal(FILETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_TYPE using the alias name FileType.
     * @param value value to set the FILE_TYPE
     */
    public void setFileType(String value) {
        setAttributeInternal(FILETYPE, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ApprovalHistoryVO.
     */
    public RowIterator getApprovalHistoryVO() {
        return (RowIterator)getAttributeInternal(APPROVALHISTORYVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
