package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 12 14:58:50 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManagerEmployeesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ManagerEmployeesVOImpl() {
    }


}
