package com.sbm.selfServices.model.views.up;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 13 02:31:49 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ManPowerRequestViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AdditionalComments {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getAdditionalComments();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAdditionalComments((String)value);
            }
        }
        ,
        Assignee {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getAssignee();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAssignee((String)value);
            }
        }
        ,
        AssigneeName {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getAssigneeName();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAssigneeName((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        Department {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDepartment();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        Duration {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDuration();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setDuration((Number)value);
            }
        }
        ,
        DurationType {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDurationType();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setDurationType((String)value);
            }
        }
        ,
        Grade {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getGrade();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setGrade((String)value);
            }
        }
        ,
        Job {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getJob();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setJob((String)value);
            }
        }
        ,
        JobDescription {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getJobDescription();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setJobDescription((String)value);
            }
        }
        ,
        Justifications {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getJustifications();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setJustifications((String)value);
            }
        }
        ,
        Language {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getLanguage();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setLanguage((String)value);
            }
        }
        ,
        ManPowerReqId {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getManPowerReqId();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setManPowerReqId((DBSequence)value);
            }
        }
        ,
        Nationality {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getNationality();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        NumberOfOpening {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getNumberOfOpening();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setNumberOfOpening((Number)value);
            }
        }
        ,
        OtherLanguage {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getOtherLanguage();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setOtherLanguage((String)value);
            }
        }
        ,
        PersonDepartment {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonDepartment();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonDepartment((String)value);
            }
        }
        ,
        PersonGrade {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonGrade();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonGrade((String)value);
            }
        }
        ,
        PersonJob {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonJob();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonJob((String)value);
            }
        }
        ,
        PersonLocation {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonLocation();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonLocation((String)value);
            }
        }
        ,
        PersonName {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonName();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonName((String)value);
            }
        }
        ,
        PersonNumber {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonNumber();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonNumber((String)value);
            }
        }
        ,
        PersonPosition {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPersonPosition();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPersonPosition((String)value);
            }
        }
        ,
        PositionCategory {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPositionCategory();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setPositionCategory((String)value);
            }
        }
        ,
        Qualifications {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getQualifications();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setQualifications((String)value);
            }
        }
        ,
        RejectionReason {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getRejectionReason();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setRejectionReason((String)value);
            }
        }
        ,
        Replacement {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getReplacement();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setReplacement((String)value);
            }
        }
        ,
        RequestStatus {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        RequisitionTitle {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getRequisitionTitle();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setRequisitionTitle((String)value);
            }
        }
        ,
        StepId {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getStepId();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setStepId((Long)value);
            }
        }
        ,
        TargetStartDate {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getTargetStartDate();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setTargetStartDate((Date)value);
            }
        }
        ,
        Years {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getYears();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setYears((Number)value);
            }
        }
        ,
        Months {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getMonths();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setMonths((Number)value);
            }
        }
        ,
        Days {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDays();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setDays((Number)value);
            }
        }
        ,
        ActionTaken {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getActionTaken();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setActionTaken((String)value);
            }
        }
        ,
        BasicSalary {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getBasicSalary();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setBasicSalary((Number)value);
            }
        }
        ,
        Experience {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getExperience();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setExperience((String)value);
            }
        }
        ,
        Type {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getType();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setType((String)value);
            }
        }
        ,
        WorkType {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getWorkType();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setWorkType((String)value);
            }
        }
        ,
        AvailableBudgect {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getAvailableBudgect();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAvailableBudgect((String)value);
            }
        }
        ,
        EditRequest {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getEditRequest();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setEditRequest((String)value);
            }
        }
        ,
        ManpowerAttachmentsEOView {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getManpowerAttachmentsEOView();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ApprovalHistoryVO {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getApprovalHistoryVO();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DepartmentsLOV1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDepartmentsLOV1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        GradesLOV1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getGradesLOV1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        JobsLOV1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getJobsLOV1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LanguageLOV1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getLanguageLOV1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PositionCategoryLOV1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getPositionCategoryLOV1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DeptEmployeesVO1 {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getDeptEmployeesVO1();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ManPowerTypeFilter {
            public Object get(ManPowerRequestViewRowImpl obj) {
                return obj.getManPowerTypeFilter();
            }

            public void put(ManPowerRequestViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ManPowerRequestViewRowImpl object);

        public abstract void put(ManPowerRequestViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ADDITIONALCOMMENTS = AttributesEnum.AdditionalComments.index();
    public static final int ASSIGNEE = AttributesEnum.Assignee.index();
    public static final int ASSIGNEENAME = AttributesEnum.AssigneeName.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int DURATIONTYPE = AttributesEnum.DurationType.index();
    public static final int GRADE = AttributesEnum.Grade.index();
    public static final int JOB = AttributesEnum.Job.index();
    public static final int JOBDESCRIPTION = AttributesEnum.JobDescription.index();
    public static final int JUSTIFICATIONS = AttributesEnum.Justifications.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int MANPOWERREQID = AttributesEnum.ManPowerReqId.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int NUMBEROFOPENING = AttributesEnum.NumberOfOpening.index();
    public static final int OTHERLANGUAGE = AttributesEnum.OtherLanguage.index();
    public static final int PERSONDEPARTMENT = AttributesEnum.PersonDepartment.index();
    public static final int PERSONGRADE = AttributesEnum.PersonGrade.index();
    public static final int PERSONJOB = AttributesEnum.PersonJob.index();
    public static final int PERSONLOCATION = AttributesEnum.PersonLocation.index();
    public static final int PERSONNAME = AttributesEnum.PersonName.index();
    public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
    public static final int PERSONPOSITION = AttributesEnum.PersonPosition.index();
    public static final int POSITIONCATEGORY = AttributesEnum.PositionCategory.index();
    public static final int QUALIFICATIONS = AttributesEnum.Qualifications.index();
    public static final int REJECTIONREASON = AttributesEnum.RejectionReason.index();
    public static final int REPLACEMENT = AttributesEnum.Replacement.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int REQUISITIONTITLE = AttributesEnum.RequisitionTitle.index();
    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int TARGETSTARTDATE = AttributesEnum.TargetStartDate.index();
    public static final int YEARS = AttributesEnum.Years.index();
    public static final int MONTHS = AttributesEnum.Months.index();
    public static final int DAYS = AttributesEnum.Days.index();
    public static final int ACTIONTAKEN = AttributesEnum.ActionTaken.index();
    public static final int BASICSALARY = AttributesEnum.BasicSalary.index();
    public static final int EXPERIENCE = AttributesEnum.Experience.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int WORKTYPE = AttributesEnum.WorkType.index();
    public static final int AVAILABLEBUDGECT = AttributesEnum.AvailableBudgect.index();
    public static final int EDITREQUEST = AttributesEnum.EditRequest.index();
    public static final int MANPOWERATTACHMENTSEOVIEW = AttributesEnum.ManpowerAttachmentsEOView.index();
    public static final int APPROVALHISTORYVO = AttributesEnum.ApprovalHistoryVO.index();
    public static final int DEPARTMENTSLOV1 = AttributesEnum.DepartmentsLOV1.index();
    public static final int GRADESLOV1 = AttributesEnum.GradesLOV1.index();
    public static final int JOBSLOV1 = AttributesEnum.JobsLOV1.index();
    public static final int LANGUAGELOV1 = AttributesEnum.LanguageLOV1.index();
    public static final int POSITIONCATEGORYLOV1 = AttributesEnum.PositionCategoryLOV1.index();
    public static final int DEPTEMPLOYEESVO1 = AttributesEnum.DeptEmployeesVO1.index();
    public static final int MANPOWERTYPEFILTER = AttributesEnum.ManPowerTypeFilter.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ManPowerRequestViewRowImpl() {
    }

    /**
     * Gets ManPowerRequest entity object.
     * @return the ManPowerRequest
     */
    public EntityImpl getManPowerRequest() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ADDITIONAL_COMMENTS using the alias name AdditionalComments.
     * @return the ADDITIONAL_COMMENTS
     */
    public String getAdditionalComments() {
        return (String) getAttributeInternal(ADDITIONALCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDITIONAL_COMMENTS using the alias name AdditionalComments.
     * @param value value to set the ADDITIONAL_COMMENTS
     */
    public void setAdditionalComments(String value) {
        setAttributeInternal(ADDITIONALCOMMENTS, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE using the alias name Assignee.
     * @return the ASSIGNEE
     */
    public String getAssignee() {
        return (String) getAttributeInternal(ASSIGNEE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE using the alias name Assignee.
     * @param value value to set the ASSIGNEE
     */
    public void setAssignee(String value) {
        setAttributeInternal(ASSIGNEE, value);
    }

    /**
     * Gets the attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @return the ASSIGNEE_NAME
     */
    public String getAssigneeName() {
        return (String) getAttributeInternal(ASSIGNEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNEE_NAME using the alias name AssigneeName.
     * @param value value to set the ASSIGNEE_NAME
     */
    public void setAssigneeName(String value) {
        setAttributeInternal(ASSIGNEENAME, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for DURATION using the alias name Duration.
     * @return the DURATION
     */
    public Number getDuration() {
        return (Number) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION using the alias name Duration.
     * @param value value to set the DURATION
     */
    public void setDuration(Number value) {
        setAttributeInternal(DURATION, value);
    }

    /**
     * Gets the attribute value for DURATION_TYPE using the alias name DurationType.
     * @return the DURATION_TYPE
     */
    public String getDurationType() {
        return (String) getAttributeInternal(DURATIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION_TYPE using the alias name DurationType.
     * @param value value to set the DURATION_TYPE
     */
    public void setDurationType(String value) {
        setAttributeInternal(DURATIONTYPE, value);
    }

    /**
     * Gets the attribute value for GRADE using the alias name Grade.
     * @return the GRADE
     */
    public String getGrade() {
        return (String) getAttributeInternal(GRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADE using the alias name Grade.
     * @param value value to set the GRADE
     */
    public void setGrade(String value) {
        setAttributeInternal(GRADE, value);
    }

    /**
     * Gets the attribute value for JOB using the alias name Job.
     * @return the JOB
     */
    public String getJob() {
        return (String) getAttributeInternal(JOB);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB using the alias name Job.
     * @param value value to set the JOB
     */
    public void setJob(String value) {
        setAttributeInternal(JOB, value);
    }

    /**
     * Gets the attribute value for JOB_DESCRIPTION using the alias name JobDescription.
     * @return the JOB_DESCRIPTION
     */
    public String getJobDescription() {
        return (String) getAttributeInternal(JOBDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_DESCRIPTION using the alias name JobDescription.
     * @param value value to set the JOB_DESCRIPTION
     */
    public void setJobDescription(String value) {
        setAttributeInternal(JOBDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for JUSTIFICATIONS using the alias name Justifications.
     * @return the JUSTIFICATIONS
     */
    public String getJustifications() {
        return (String) getAttributeInternal(JUSTIFICATIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for JUSTIFICATIONS using the alias name Justifications.
     * @param value value to set the JUSTIFICATIONS
     */
    public void setJustifications(String value) {
        setAttributeInternal(JUSTIFICATIONS, value);
    }

    /**
     * Gets the attribute value for LANGUAGE using the alias name Language.
     * @return the LANGUAGE
     */
    public String getLanguage() {
        return (String) getAttributeInternal(LANGUAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANGUAGE using the alias name Language.
     * @param value value to set the LANGUAGE
     */
    public void setLanguage(String value) {
        setAttributeInternal(LANGUAGE, value);
    }

    /**
     * Gets the attribute value for MAN_POWER_REQ_ID using the alias name ManPowerReqId.
     * @return the MAN_POWER_REQ_ID
     */
    public DBSequence getManPowerReqId() {
        return (DBSequence)getAttributeInternal(MANPOWERREQID);
    }

    /**
     * Sets <code>value</code> as attribute value for MAN_POWER_REQ_ID using the alias name ManPowerReqId.
     * @param value value to set the MAN_POWER_REQ_ID
     */
    public void setManPowerReqId(DBSequence value) {
        setAttributeInternal(MANPOWERREQID, value);
    }

    /**
     * Gets the attribute value for NATIONALITY using the alias name Nationality.
     * @return the NATIONALITY
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY using the alias name Nationality.
     * @param value value to set the NATIONALITY
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for NUMBER_OF_OPENING using the alias name NumberOfOpening.
     * @return the NUMBER_OF_OPENING
     */
    public Number getNumberOfOpening() {
        return (Number) getAttributeInternal(NUMBEROFOPENING);
    }

    /**
     * Sets <code>value</code> as attribute value for NUMBER_OF_OPENING using the alias name NumberOfOpening.
     * @param value value to set the NUMBER_OF_OPENING
     */
    public void setNumberOfOpening(Number value) {
        setAttributeInternal(NUMBEROFOPENING, value);
    }

    /**
     * Gets the attribute value for OTHER_LANGUAGE using the alias name OtherLanguage.
     * @return the OTHER_LANGUAGE
     */
    public String getOtherLanguage() {
        return (String) getAttributeInternal(OTHERLANGUAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_LANGUAGE using the alias name OtherLanguage.
     * @param value value to set the OTHER_LANGUAGE
     */
    public void setOtherLanguage(String value) {
        setAttributeInternal(OTHERLANGUAGE, value);
    }

    /**
     * Gets the attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @return the PERSON_DEPARTMENT
     */
    public String getPersonDepartment() {
        return (String) getAttributeInternal(PERSONDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_DEPARTMENT using the alias name PersonDepartment.
     * @param value value to set the PERSON_DEPARTMENT
     */
    public void setPersonDepartment(String value) {
        setAttributeInternal(PERSONDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for PERSON_GRADE using the alias name PersonGrade.
     * @return the PERSON_GRADE
     */
    public String getPersonGrade() {
        return (String) getAttributeInternal(PERSONGRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_GRADE using the alias name PersonGrade.
     * @param value value to set the PERSON_GRADE
     */
    public void setPersonGrade(String value) {
        setAttributeInternal(PERSONGRADE, value);
    }

    /**
     * Gets the attribute value for PERSON_JOB using the alias name PersonJob.
     * @return the PERSON_JOB
     */
    public String getPersonJob() {
        return (String) getAttributeInternal(PERSONJOB);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_JOB using the alias name PersonJob.
     * @param value value to set the PERSON_JOB
     */
    public void setPersonJob(String value) {
        setAttributeInternal(PERSONJOB, value);
    }

    /**
     * Gets the attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @return the PERSON_LOCATION
     */
    public String getPersonLocation() {
        return (String) getAttributeInternal(PERSONLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_LOCATION using the alias name PersonLocation.
     * @param value value to set the PERSON_LOCATION
     */
    public void setPersonLocation(String value) {
        setAttributeInternal(PERSONLOCATION, value);
    }

    /**
     * Gets the attribute value for PERSON_NAME using the alias name PersonName.
     * @return the PERSON_NAME
     */
    public String getPersonName() {
        return (String) getAttributeInternal(PERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NAME using the alias name PersonName.
     * @param value value to set the PERSON_NAME
     */
    public void setPersonName(String value) {
        setAttributeInternal(PERSONNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @return the PERSON_NUMBER
     */
    public String getPersonNumber() {
        return (String) getAttributeInternal(PERSONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @param value value to set the PERSON_NUMBER
     */
    public void setPersonNumber(String value) {
        setAttributeInternal(PERSONNUMBER, value);
    }

    /**
     * Gets the attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @return the PERSON_POSITION
     */
    public String getPersonPosition() {
        return (String) getAttributeInternal(PERSONPOSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_POSITION using the alias name PersonPosition.
     * @param value value to set the PERSON_POSITION
     */
    public void setPersonPosition(String value) {
        setAttributeInternal(PERSONPOSITION, value);
    }

    /**
     * Gets the attribute value for POSITION_CATEGORY using the alias name PositionCategory.
     * @return the POSITION_CATEGORY
     */
    public String getPositionCategory() {
        return (String) getAttributeInternal(POSITIONCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSITION_CATEGORY using the alias name PositionCategory.
     * @param value value to set the POSITION_CATEGORY
     */
    public void setPositionCategory(String value) {
        setAttributeInternal(POSITIONCATEGORY, value);
    }

    /**
     * Gets the attribute value for QUALIFICATIONS using the alias name Qualifications.
     * @return the QUALIFICATIONS
     */
    public String getQualifications() {
        return (String) getAttributeInternal(QUALIFICATIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFICATIONS using the alias name Qualifications.
     * @param value value to set the QUALIFICATIONS
     */
    public void setQualifications(String value) {
        setAttributeInternal(QUALIFICATIONS, value);
    }

    /**
     * Gets the attribute value for REJECTION_REASON using the alias name RejectionReason.
     * @return the REJECTION_REASON
     */
    public String getRejectionReason() {
        return (String) getAttributeInternal(REJECTIONREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECTION_REASON using the alias name RejectionReason.
     * @param value value to set the REJECTION_REASON
     */
    public void setRejectionReason(String value) {
        setAttributeInternal(REJECTIONREASON, value);
    }

    /**
     * Gets the attribute value for REPLACEMENT using the alias name Replacement.
     * @return the REPLACEMENT
     */
    public String getReplacement() {
        return (String) getAttributeInternal(REPLACEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for REPLACEMENT using the alias name Replacement.
     * @param value value to set the REPLACEMENT
     */
    public void setReplacement(String value) {
        setAttributeInternal(REPLACEMENT, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the attribute value for REQUISITION_TITLE using the alias name RequisitionTitle.
     * @return the REQUISITION_TITLE
     */
    public String getRequisitionTitle() {
        return (String) getAttributeInternal(REQUISITIONTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUISITION_TITLE using the alias name RequisitionTitle.
     * @param value value to set the REQUISITION_TITLE
     */
    public void setRequisitionTitle(String value) {
        setAttributeInternal(REQUISITIONTITLE, value);
    }

    /**
     * Gets the attribute value for STEP_ID using the alias name StepId.
     * @return the STEP_ID
     */
    public Long getStepId() {
        return (Long) getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as attribute value for STEP_ID using the alias name StepId.
     * @param value value to set the STEP_ID
     */
    public void setStepId(Long value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for TARGET_START_DATE using the alias name TargetStartDate.
     * @return the TARGET_START_DATE
     */
    public Date getTargetStartDate() {
        return (Date) getAttributeInternal(TARGETSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_START_DATE using the alias name TargetStartDate.
     * @param value value to set the TARGET_START_DATE
     */
    public void setTargetStartDate(Date value) {
        setAttributeInternal(TARGETSTARTDATE, value);
    }

    /**
     * Gets the attribute value for YEARS using the alias name Years.
     * @return the YEARS
     */
    public Number getYears() {
        return (Number) getAttributeInternal(YEARS);
    }

    /**
     * Sets <code>value</code> as attribute value for YEARS using the alias name Years.
     * @param value value to set the YEARS
     */
    public void setYears(Number value) {
        setAttributeInternal(YEARS, value);
    }

    /**
     * Gets the attribute value for MONTHS using the alias name Months.
     * @return the MONTHS
     */
    public Number getMonths() {
        return (Number) getAttributeInternal(MONTHS);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTHS using the alias name Months.
     * @param value value to set the MONTHS
     */
    public void setMonths(Number value) {
        setAttributeInternal(MONTHS, value);
    }

    /**
     * Gets the attribute value for DAYS using the alias name Days.
     * @return the DAYS
     */
    public Number getDays() {
        return (Number) getAttributeInternal(DAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for DAYS using the alias name Days.
     * @param value value to set the DAYS
     */
    public void setDays(Number value) {
        setAttributeInternal(DAYS, value);
    }

    /**
     * Gets the attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @return the ACTION_TAKEN
     */
    public String getActionTaken() {
        return (String) getAttributeInternal(ACTIONTAKEN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @param value value to set the ACTION_TAKEN
     */
    public void setActionTaken(String value) {
        setAttributeInternal(ACTIONTAKEN, value);
    }

    /**
     * Gets the attribute value for BASIC_SALARY using the alias name BasicSalary.
     * @return the BASIC_SALARY
     */
    public Number getBasicSalary() {
        return (Number) getAttributeInternal(BASICSALARY);
    }

    /**
     * Sets <code>value</code> as attribute value for BASIC_SALARY using the alias name BasicSalary.
     * @param value value to set the BASIC_SALARY
     */
    public void setBasicSalary(Number value) {
        setAttributeInternal(BASICSALARY, value);
    }

    /**
     * Gets the attribute value for EXPERIENCE using the alias name Experience.
     * @return the EXPERIENCE
     */
    public String getExperience() {
        return (String) getAttributeInternal(EXPERIENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPERIENCE using the alias name Experience.
     * @param value value to set the EXPERIENCE
     */
    public void setExperience(String value) {
        setAttributeInternal(EXPERIENCE, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for WORK_TYPE using the alias name WorkType.
     * @return the WORK_TYPE
     */
    public String getWorkType() {
        return (String) getAttributeInternal(WORKTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_TYPE using the alias name WorkType.
     * @param value value to set the WORK_TYPE
     */
    public void setWorkType(String value) {
        setAttributeInternal(WORKTYPE, value);
    }

    /**
     * Gets the attribute value for AVAILABLE_BUDGECT using the alias name AvailableBudgect.
     * @return the AVAILABLE_BUDGECT
     */
    public String getAvailableBudgect() {
        return (String) getAttributeInternal(AVAILABLEBUDGECT);
    }

    /**
     * Sets <code>value</code> as attribute value for AVAILABLE_BUDGECT using the alias name AvailableBudgect.
     * @param value value to set the AVAILABLE_BUDGECT
     */
    public void setAvailableBudgect(String value) {
        setAttributeInternal(AVAILABLEBUDGECT, value);
    }


    /**
     * Gets the attribute value for EDIT_REQUEST using the alias name EditRequest.
     * @return the EDIT_REQUEST
     */
    public String getEditRequest() {
        return (String) getAttributeInternal(EDITREQUEST);
    }

    /**
     * Sets <code>value</code> as attribute value for EDIT_REQUEST using the alias name EditRequest.
     * @param value value to set the EDIT_REQUEST
     */
    public void setEditRequest(String value) {
        setAttributeInternal(EDITREQUEST, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ManpowerAttachmentsEOView.
     */
    public RowIterator getManpowerAttachmentsEOView() {
        return (RowIterator)getAttributeInternal(MANPOWERATTACHMENTSEOVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ApprovalHistoryVO.
     */
    public RowIterator getApprovalHistoryVO() {
        return (RowIterator)getAttributeInternal(APPROVALHISTORYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartmentsLOV1.
     */
    public RowSet getDepartmentsLOV1() {
        return (RowSet)getAttributeInternal(DEPARTMENTSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GradesLOV1.
     */
    public RowSet getGradesLOV1() {
        return (RowSet)getAttributeInternal(GRADESLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> JobsLOV1.
     */
    public RowSet getJobsLOV1() {
        return (RowSet)getAttributeInternal(JOBSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LanguageLOV1.
     */
    public RowSet getLanguageLOV1() {
        return (RowSet)getAttributeInternal(LANGUAGELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PositionCategoryLOV1.
     */
    public RowSet getPositionCategoryLOV1() {
        return (RowSet)getAttributeInternal(POSITIONCATEGORYLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DeptEmployeesVO1.
     */
    public RowSet getDeptEmployeesVO1() {
        return (RowSet)getAttributeInternal(DEPTEMPLOYEESVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ManPowerTypeFilter.
     */
    public RowSet getManPowerTypeFilter() {
        return (RowSet)getAttributeInternal(MANPOWERTYPEFILTER);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
