package com.sbm.selfServices.model.views.up;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 24 19:19:22 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestVisibleSetupVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RequestVisibleSetupVOImpl() {
    }

    /**
     * Returns the variable value for BV_LOC_ID.
     * @return variable value for BV_LOC_ID
     */
    public String getBV_LOC_ID() {
        return (String)ensureVariableManager().getVariableValue("BV_LOC_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_LOC_ID.
     * @param value value to bind as BV_LOC_ID
     */
    public void setBV_LOC_ID(String value) {
        ensureVariableManager().setVariableValue("BV_LOC_ID", value);
    }
}
