package com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2;

import com.sun.xml.ws.api.addressing.AddressingVersion;
import com.sun.xml.ws.api.message.Header;
import com.sun.xml.ws.api.message.HeaderList;
import com.sun.xml.ws.developer.JAXWSProperties;

import javax.annotation.Resource;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.soap.Addressing;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/",
  name="UserDetailsServiceResponse")
@XmlSeeAlso(
  { sdo.commonj.java.ObjectFactory.class, com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class, sdo.commonj.ObjectFactory.class, com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class, com.oracle.xmlns.adf.svc.errors.ObjectFactory.class, com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT)
@Addressing(enabled=true, required=true)
public class UserDetailsServiceResponseImpl
{
  @Resource
  private WebServiceContext wsContext;

  private static final AddressingVersion WS_ADDR_VER = AddressingVersion.W3C;

  @WebMethod(action="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault")
  @Oneway
  public void onFault(@WebParam(targetNamespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0",
      partName="parameters", name="Fault")
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.FaultType parameters)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("parameters: '" + parameters + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByPersonIdAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByPersonIdAsyncResponse")
  @RequestWrapper(localName="findUserDetailsByPersonIdAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.FindUserDetailsByPersonIdAsyncResponse")
  @Oneway
  public void findUserDetailsByPersonIdAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.UserDetailsResult result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findSelfUserDetailsAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findSelfUserDetailsAsyncResponse")
  @RequestWrapper(localName="findSelfUserDetailsAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.FindSelfUserDetailsAsyncResponse")
  @Oneway
  public void findSelfUserDetailsAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.UserDetailsResult result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByUsernameAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByUsernameAsyncResponse")
  @RequestWrapper(localName="findUserDetailsByUsernameAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.FindUserDetailsByUsernameAsyncResponse")
  @Oneway
  public void findUserDetailsByUsernameAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.UserDetailsResult result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByPersonNumberAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/findUserDetailsByPersonNumberAsyncResponse")
  @RequestWrapper(localName="findUserDetailsByPersonNumberAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.FindUserDetailsByPersonNumberAsyncResponse")
  @Oneway
  public void findUserDetailsByPersonNumberAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.UserDetailsResult result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getEntityListAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getEntityListAsyncResponse")
  @RequestWrapper(localName="getEntityListAsyncResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.GetEntityListAsyncResponse")
  @Oneway
  public void getEntityListAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo> result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getDfltObjAttrHintsAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getDfltObjAttrHintsAsyncResponse")
  @RequestWrapper(localName="getDfltObjAttrHintsAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.GetDfltObjAttrHintsAsyncResponse")
  @Oneway
  public void getDfltObjAttrHintsAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    com.oracle.xmlns.adf.svc.types.ObjAttrHints result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getServiceLastUpdateTimeAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/getServiceLastUpdateTimeAsyncResponse")
  @RequestWrapper(localName="getServiceLastUpdateTimeAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
    className="com.oracle.xmlns.apps.hcm.people.roles.userdetailsservicev2.types.GetServiceLastUpdateTimeAsyncResponse")
  @Oneway
  public void getServiceLastUpdateTimeAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/types/",
      name="result")
    XMLGregorianCalendar result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }
}
