package com.oracle.xmlns.oxp.service.v2;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://egwo-dev1.fa.em2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl",
  targetNamespace="http://xmlns.oracle.com/oxp/service/v2", name="ReportService")
public class ReportService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.oracle.xmlns.oxp.service.v2.ReportService_Service");
      URL baseUrl = ReportService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ReportService_Service.class.getResource("https://egwo-dev1.fa.em2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://egwo-dev1.fa.em2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://egwo-dev1.fa.em2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://egwo-dev1.fa.em2.oraclecloud.com/xmlpserver/services/v2/ReportService?wsdl",
          e);
    }
  }

  public ReportService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/oxp/service/v2",
                    "ReportService"));
  }

  public ReportService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ReportService")
  public com.oracle.xmlns.oxp.service.v2.ReportService getReportService()
  {
    return (com.oracle.xmlns.oxp.service.v2.ReportService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/v2",
                                                                                   "ReportService"),
                                                                         com.oracle.xmlns.oxp.service.v2.ReportService.class);
  }

  @WebEndpoint(name="ReportService")
  public com.oracle.xmlns.oxp.service.v2.ReportService getReportService(WebServiceFeature... features)
  {
    return (com.oracle.xmlns.oxp.service.v2.ReportService) super.getPort(new QName("http://xmlns.oracle.com/oxp/service/v2",
                                                                                   "ReportService"),
                                                                         com.oracle.xmlns.oxp.service.v2.ReportService.class,
                                                                         features);
  }
}
