package com.sbm.selfServices.model.views.staticlov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 07 15:58:22 AST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpecialEditStatVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SpecialEditStatVOImpl() {
    }
}

